import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const dossier='11111111-1111-4111-8111-111111111111',entry='22222222-2222-4222-8222-222222222222';
function route({owner=true,rpcError=null,authenticated=true}={}){const calls=[];const client={auth:{getUser:async()=>({data:{user:authenticated?{id:'owner'}:null},error:null})},rpc:async(name,args)=>{calls.push({name,args});return {data:[],error:rpcError};},from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:owner?{id:dossier}:null,error:null})})};const code=ts.transpileModule(readFileSync(new URL('../app/api/library/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2023}}).outputText;const m={exports:{}};new Function('require','module','exports',code)(n=>{if(n==='next/server')return {NextResponse:{json:(v,o)=>new Response(JSON.stringify(v),o)}};if(n==='@/lib/supabase/server')return {createClient:async()=>client};if(n==='@/lib/library')return {libraryId:v=>typeof v==='string'&&/^[0-9a-f-]{36}$/.test(v),libraryText:v=>v,librarySources:v=>v};throw Error(n);},m,m.exports);return {...m.exports,calls};}
const req=body=>new Request('https://test.local/api/library',{method:'POST',headers:{origin:'https://test.local','content-type':'application/json'},body:JSON.stringify(body)});
test('editor append delegates permissions and author to SQL, never takes owner/actor from client',async()=>{const r=route({owner:false});const response=await r.POST(req({action:'save',id:entry,dossierId:dossier,title:'Nota',body:'Texto',sources:[],revisionOf:entry,owner_id:'forged'}));assert.equal(response.status,200);assert.equal(r.calls[0].name,'research_append');assert.equal(r.calls[0].args.p_revision,entry);assert.equal(r.calls[0].args.owner_id,undefined);});
test('revoked editor is denied and cannot fall back to direct insertion',async()=>{const r=route({rpcError:{message:'FORBIDDEN'}});assert.equal((await r.POST(req({action:'save',id:entry,dossierId:dossier,title:'x',body:'x',sources:[]}))).status,403);assert.equal(r.calls.length,1);});
test('sharing is owner-only, requires explicit valid role and rejects CSRF/login failures',async()=>{const payload={action:'share',dossierId:dossier,organizationId:entry,memberId:entry,allow:true,role:'editor'};const denied=route({owner:false});assert.equal((await denied.POST(req(payload))).status,403);assert.equal(denied.calls.length,0);const r=route();assert.equal((await r.POST(req({...payload,role:'owner'}))).status,400);assert.equal((await r.POST(req(payload))).status,200);assert.equal(r.calls[0].args.p_role,'editor');const bad=req(payload);bad.headers.set('origin','https://attacker.test');assert.equal((await r.POST(bad)).status,403);assert.equal((await route({authenticated:false}).POST(req(payload))).status,401);});
