import test from 'node:test';
import assert from 'node:assert/strict';
import {trackedWord} from '../lib/word-review.ts';
import {qualityReport,reviewCriteria} from '../lib/quality-review.ts';
function unpack(bytes){const b=Buffer.from(bytes),files={};let p=0;while(b.readUInt32LE(p)===0x04034b50){const size=b.readUInt32LE(p+18),len=b.readUInt16LE(p+26);assert.equal(b.readUInt16LE(p+8),0);const name=b.subarray(p+30,p+30+len).toString();files[name]=b.subarray(p+30+len,p+30+len+size).toString();p+=30+len+size;}assert.equal(b.readUInt32LE(p),0x02014b50);assert.equal(b.readUInt32LE(b.length-22),0x06054b50);assert.equal(b.readUInt32LE(b.length-6),p);return files;}
test('Word package has real revisions, author/date and no external relationships',()=>{const files=unpack(trackedWord('A & B\nRetirar','A & B\nInserir <texto>','Ana "Teste"',new Date('2026-01-01T00:00:00Z')));assert.equal(Object.keys(files).length,5);const xml=files['word/document.xml'];assert.match(xml,/<w:del /);assert.match(xml,/<w:ins /);assert.match(xml,/<w:delText xml:space="preserve">Retirar/);assert.match(xml,/Inserir &lt;texto&gt;/);assert.match(xml,/Ana &quot;Teste&quot;/);assert.match(xml,/<w:rPr><w:del /);assert.match(files['word/settings.xml'],/<w:trackRevisions/);for(const value of Object.values(files))assert.doesNotMatch(value,/TargetMode="External"|<script/);});
test('identical text produces no spurious revisions and invalid inputs cannot export',()=>{const xml=unpack(trackedWord('Texto','Texto','Ana'))['word/document.xml'];assert.doesNotMatch(xml,/<w:(ins|del) /);for(const args of [['','B','Ana'],['A','B',''],['x'.repeat(60001),'B','Ana'],['A','a\n'.repeat(2001),'Ana']])assert.throws(()=>trackedWord(...args));});
test('deleted or inserted final paragraphs are tracked including paragraph marks',()=>{for(const [a,b,kind] of [['A\nB','A','del'],['A','A\nB','ins']]){const xml=unpack(trackedWord(a,b,'Ana'))['word/document.xml'];assert.match(xml,new RegExp(`<w:rPr><w:${kind} `));assert.equal((xml.match(/w:id="/g)||[]).length,2);}});
const base=()=>({caseName:'Caso fictício',reviewer:'Revisor',model:'não verificado',answer:'Resposta fictícia',notes:'',scores:reviewCriteria.map(()=>'pending'),seconds:'',cost:''});
test('evaluations start incomplete, never claim a verified lawyer, and require evidence',()=>{const report=qualityReport(base());assert.match(report,/INCOMPLETA/);assert.match(report,/identidade não verificada/);assert.match(report,/Não medido/);assert.throws(()=>qualityReport({...base(),scores:reviewCriteria.map(()=>'pass')}));const failed=qualityReport({...base(),scores:['fail',...reviewCriteria.slice(1).map(()=>'pending')],notes:'Fonte não sustenta a afirmação.'});assert.match(failed,/REPROVADA/);});
test('evaluation rejects malformed scores, overlong input, negative or non-finite metrics',()=>{for(const patch of [{scores:[]},{scores:reviewCriteria.map(()=>'approved')},{answer:'x'.repeat(60001)},{cost:'-1'},{seconds:'Infinity'},{cost:'1e99'}])assert.throws(()=>qualityReport({...base(),...patch}));assert.match(qualityReport({...base(),cost:'0,25',seconds:'3'}),/0,25/);assert.match(qualityReport({...base(),scores:reviewCriteria.map(()=>'na'),notes:'Caso sem matéria jurídica.'}),/não avaliada/);});
