import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
function load(file,deps={},env={}){const out={};const js=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports','process',js)(id=>{if(!(id in deps))throw Error(id);return deps[id];},out,{env});return out;}
const response={NextResponse:{json:(body,options={})=>({body,status:options.status||200})}};
function db(result={data:[{id:'one'}],error:null}){const calls=[];const q={then:(resolve,reject)=>Promise.resolve(result).then(resolve,reject)};for(const method of ['insert','update','delete','eq','gt','lt','select','order','limit','maybeSingle','single'])q[method]=(...args)=>{calls.push([method,...args]);return q;};return {calls,from:table=>{calls.push(['from',table]);return q;},rpc:async(...args)=>{calls.push(['rpc',...args]);return result;}};}
test('recovery is explicit opt-in and never persists inputs',async()=>{const api=load('../lib/result-recovery.ts',{'server-only':{}}),store=db();assert.equal(await api.beginRecovery(store,new Request('https://site.test'),'id','actor','assistant'),false);assert.equal(store.calls.length,0);assert.equal(await api.beginRecovery(store,new Request('https://site.test',{headers:{'x-recovery-consent':'true'}}),'id','actor','assistant','org',['doc']),true);assert.deepEqual(store.calls[1],['insert',{id:'id',actor_id:'actor',kind:'assistant',organization_id:'org',document_ids:['doc']}]);});
test('save is actor and expiry scoped; failures never claim recovery succeeded',async()=>{const api=load('../lib/result-recovery.ts',{'server-only':{}}),store=db();await api.saveRecovery(store,'id','actor',{text:'answer'});assert.ok(store.calls.some(c=>c[0]==='eq'&&c[1]==='actor_id'&&c[2]==='actor'));assert.ok(store.calls.some(c=>c[0]==='gt'&&c[1]==='expires_at'));await assert.rejects(api.saveRecovery(db({data:[],error:null}),'id','actor',{}),/RECOVERY_SAVE/);await api.uncertainRecovery(store,'id','actor');assert.deepEqual(store.calls.at(-1),['eq','state','processing']);});
test('recovery listing requires verified authentication before admin access',async()=>{let touched=false;const api=load('../app/api/recoveries/route.ts',{'next/server':response,'@/lib/supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user:null}})}})},'@/lib/supabase/admin':{createAdminClient:()=>{touched=true;}}});assert.equal((await api.GET()).status,401);assert.equal(touched,false);});
test('recovery listing scopes actor and expiry and hides documents with revoked access',async()=>{const store=db({data:[{id:'one',organization_id:'org',document_ids:['doc'],state:'completed',result:{text:'private'}}],error:null});const client={auth:{getUser:async()=>({data:{user:{id:'actor',email_confirmed_at:'yes'}}})},from:()=>db({data:null,error:null}).from('organization_members')};const api=load('../app/api/recoveries/route.ts',{'next/server':response,'@/lib/supabase/server':{createClient:async()=>client},'@/lib/supabase/admin':{createAdminClient:()=>store}});const r=await api.GET();assert.equal(r.status,200);assert.deepEqual(r.body.results,[]);assert.ok(store.calls.some(c=>c[0]==='eq'&&c[1]==='actor_id'&&c[2]==='actor'));assert.ok(store.calls.some(c=>c[0]==='gt'&&c[1]==='expires_at'));});
const url='https://site.test/api/reconcile?id=10000000-0000-4000-8000-000000000001';
test('reconciliation refuses non-owner and foreign origin without touching balances',async()=>{for(const [owner,origin] of [[false,'https://site.test'],[true,'https://evil.test']]){const api=load('../app/api/reconcile/route.ts',{'next/server':response,'@/lib/site-owner':{isSiteOwner:async()=>owner},'@/lib/supabase/admin':{createAdminClient:()=>{throw Error('must not access');}}});assert.equal((await api.POST(new Request(url,{method:'POST',headers:{origin}}))).status,403);}});
test('reconciliation uses recorded actor and preserves unconfirmed reserves',async()=>{for(const error of [null,{message:'METER_UNCONFIRMED'}]){const store=db({data:{actor_id:'actor'},error:null});store.rpc=async(name,args)=>{assert.equal(name,'ai_meter_settle');assert.equal(args.p_actor,'actor');return {data:error?null:42,error};};const api=load('../app/api/reconcile/route.ts',{'next/server':response,'@/lib/site-owner':{isSiteOwner:async()=>true},'@/lib/supabase/admin':{createAdminClient:()=>store}});const r=await api.POST(new Request(url,{method:'POST',headers:{origin:'https://site.test'}}));assert.equal(r.status,error?409:200);if(!error)assert.equal(r.body.chargedCents,42);}});
test('scheduled cleanup requires secret and deletes only expired records',async()=>{const store=db();const api=load('../app/api/maintenance/recovery/route.ts',{'next/server':response,'@/lib/supabase/admin':{createAdminClient:()=>store}},{CRON_SECRET:'x'.repeat(32)});assert.equal((await api.GET(new Request('https://site.test'))).status,401);assert.equal(store.calls.length,0);assert.equal((await api.GET(new Request('https://site.test',{headers:{authorization:'Bearer '+'x'.repeat(32)}}))).status,200);assert.ok(store.calls.some(c=>c[0]==='lt'&&c[1]==='expires_at'));});
test('opted-in transcription stores a validated result once; missing migration blocks generation',async()=>{
 for(const missing of [false,true]){
  const store=db({data:[{id:'one'}],error:missing?{message:'missing table'}:null});store.rpc=async()=>({error:null});let generations=0,afters=0;
  class Provider{audio={transcriptions:{create:()=>({withResponse:async()=>{generations++;return {data:{text:'Resultado final.'},response:new Response()};}})}};}
  const route=load('../app/api/transcription/route.ts',{'next/server':{...response,after:()=>{afters++;}},'@/lib/result-recovery':load('../lib/result-recovery.ts',{'server-only':{}}),openai:{default:Provider,toFile:async()=>({})},'@/lib/supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:'actor'}}})}})},'@/lib/supabase/admin':{createAdminClient:()=>store},'@/lib/billing-access':{paidAIAccessError:()=>''},'@/lib/ai-pilot':{pilotMessages:{},validatePilotWav:()=>{}},'@/lib/service-funding':{serviceAccessError:()=>'',reserveService:async()=>null},'@/lib/commercial-meter':{meterMessages:{}},'@/lib/transcription':load('../lib/transcription.ts')},{AI_EXECUTION_ENABLED:'true',OPENAI_API_KEY:'fixture'});
  const result=await route.POST(new Request('https://site.test/api/transcription',{method:'POST',headers:{origin:'https://site.test','x-request-id':'10000000-0000-4000-8000-000000000001','x-audio-consent':'true','x-audio-extension':'wav','x-recovery-consent':'true'},body:Buffer.from('RIFF0000WAVEdata0000')}));
  assert.equal(result.status,missing?503:200);assert.equal(generations,missing?0:1);assert.equal(afters,1);
  if(!missing){const saved=store.calls.find(c=>c[0]==='update'&&c[1].state==='completed');assert.equal(saved[1].result.text,'Resultado final.');assert.equal(store.calls.filter(c=>c[0]==='insert').length,1);}
 }
});
