import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
function load(path,deps,env={}){const module={exports:{}};const source=ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;new Function('require','module','exports','process','console',source)(n=>{if(!(n in deps))throw Error(n);return deps[n];},module,module.exports,{env:{AI_EXECUTION_ENABLED:'true',OPENAI_API_KEY:'test',...env}},{warn(){}});return module.exports;}
const actor='10000000-0000-4000-8000-000000000001',id='20000000-0000-4000-8000-000000000001';
const input={requestId:id,mode:'research',profile:'Geral',country:'Portugal',question:'Pergunta pública',history:[],documentIds:[],consent:true};
const result={text:'Resposta com fontes',citations:[],researched:true,generatedAt:new Date().toISOString()};
const assistant={validateAssistantInput:v=>{if(!v||v.consent!==true)throw Error('INVALID_REQUEST');return v;},assistantInstructions:()=> 'Instruções',parseAssistantResponse:r=>{if(r.status!=='completed')throw Error('INCOMPLETE');return result;}};
const models=load('../lib/research-models.ts',{'./assistant':assistant});
const jobs=load('../lib/research-jobs.ts',{'./assistant':assistant});
function setup(options={}){
 const rows=new Map(),calls=[],rpc=[];let reservations=0;
 const admin={from(){let op='read',values,filters=[],limit=999;const q={select(){return q;},insert(v){op='insert';values=v;return q;},update(v){op='update';values=v;return q;},delete(){op='delete';return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},gt(k,v){filters.push(r=>r[k]>v);return q;},lt(k,v){filters.push(r=>r[k]<v);return q;},in(k,v){filters.push(r=>v.includes(r[k]));return q;},order(){return q;},limit(v){limit=v;return q;},single(){return Promise.resolve(exec());},maybeSingle(){return Promise.resolve(exec());},then(ok,bad){return Promise.resolve(exec()).then(ok,bad);}};function exec(){if(op==='insert'){if(rows.has(values.id)||[...rows.values()].some(r=>r.owner_id===values.owner_id&&!['completed','failed'].includes(r.state)))return {error:{code:'23505'}};const r={state:'starting',updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString(),...values};rows.set(r.id,r);return {data:structuredClone(r)};}const found=[...rows.values()].filter(r=>filters.every(f=>f(r))).slice(0,limit);if(op==='update')for(const r of found)Object.assign(r,values);if(op==='delete')for(const r of found)rows.delete(r.id);return {data:found[0]?structuredClone(found[0]):null};}return q;},rpc:async(n,args)=>{rpc.push([n,args]);return {data:true};}};
 class AI{models={retrieve:async()=>{if(options.unavailable)throw Error('unavailable');return {};}};static APIConnectionTimeoutError=class extends Error{};constructor(o){assert.equal(o.maxRetries,0);}async post(path,params){calls.push(params.body);if(options.submitError)throw new AI.APIConnectionTimeoutError();return {id:'resp_'+calls.length,status:'queued'};}async get(){if(options.pollError)throw Error('network');return {status:options.status??'completed'};}}
 const route=load('../app/api/research/route.ts',{'next/server':{NextResponse:{json:(b,o)=>new Response(JSON.stringify(b),o)}},openai:AI,'@/lib/supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user:options.noUser?null:{id:actor}}})}})},'@/lib/supabase/admin':{createAdminClient:()=>admin},'@/lib/billing-access':{paidAIAccessError:()=>options.denied?'FORBIDDEN':''},'@/lib/ai-pilot':{PILOT_MODEL:'gpt-5-mini',pilotMessages:{},reservePilot:async()=>{reservations++;}},'@/lib/assistant':assistant,'@/lib/research-jobs':jobs,'@/lib/research-models':models},options.env);
 return {rows,calls,rpc,get:route.GET,reservations:()=>reservations,post:(body,origin='https://lic.test')=>route.POST(new Request('https://lic.test/api/research',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)}))};
}
const start={action:'start',input,backgroundConsent:true},advance={action:'advance',id};
test('unavailable advanced model fails before reserving; available model researches economically then reviews with bounded Astra',async()=>{const denied=setup({unavailable:true});assert.equal((await denied.post({...start,model:'gpt-6-astra'})).status,503);assert.equal(denied.reservations(),0);assert.equal(denied.calls.length,0);const s=setup();await s.post({...start,model:'gpt-6-astra'});await s.post(advance);assert.equal(s.calls[0].model,'gpt-5-mini');assert.equal(s.calls[1].model,'gpt-6-astra');assert.equal(s.calls[1].tools,undefined);assert.equal(s.reservations(),1);});
test('null JSON is rejected without charging',async()=>{const s=setup();assert.equal((await s.post(null)).status,400);assert.equal(s.reservations(),0);});
test('background generation returns job ID, recovers and reserves only once',async()=>{const s=setup();assert.equal((await s.post(start)).status,200);assert.equal(s.calls[0].background,true);assert.equal(s.calls[0].store,false);assert.equal(s.reservations(),1);await s.post(start);assert.equal(s.calls.length,1);assert.equal((await (await s.get()).json()).job.id,id);});
test('concurrent polls create one review and never expose draft',async()=>{const s=setup();await s.post(start);const responses=await Promise.all([s.post(advance),s.post(advance)]);assert.equal(s.calls.length,2);for(const r of responses)assert.equal((await r.json()).job.result,undefined);const done=await (await s.post(advance)).json();assert.equal(done.job.state,'completed');assert.equal(done.job.result.review,'second-pass');await s.post(advance);assert.equal(s.calls.length,2);assert.equal(s.reservations(),1);});
test('failed retrieval retains provider ID without submitting again',async()=>{const s=setup({pollError:true});await s.post(start);assert.equal((await s.post(advance)).status,503);assert.equal(s.rows.get(id).state,'draft');assert.equal(s.calls.length,1);});
test('uncertain submission becomes failed, same ID cannot start again',async()=>{const s=setup({submitError:true});await s.post(start);assert.equal(s.rows.get(id).state,'failed');await s.post(start);assert.equal(s.calls.length,1);});
test('cross-user recovery does not expose prompt or result',async()=>{const s=setup();s.rows.set(id,{id,owner_id:'other',input,state:'completed',result,expires_at:new Date(Date.now()+86400000).toISOString()});assert.equal((await s.post(advance)).status,404);assert.equal((await (await s.get()).json()).job,null);});
test('consent, private mode, model, origin, auth and pause fail before spend',async()=>{for(const [opts,body,origin] of [[{}, {...start,backgroundConsent:false}], [{},{...start,input:{...input,mode:'document'}}],[{},{...start,model:'unknown-model'}],[{},start,'https://evil.test'],[{noUser:true},start],[{denied:true},start],[{env:{AI_EXECUTION_ENABLED:'false'}},start]]){const s=setup(opts);assert.ok((await s.post(body,origin)).status>=400);assert.equal(s.calls.length,0);assert.equal(s.reservations(),0);}});
test('expired processing never recreates response',async()=>{const s=setup();await s.post(start);s.rows.get(id).updated_at=new Date(Date.now()-9*60000).toISOString();const r=await (await s.post(advance)).json();assert.equal(r.job.state,'failed');assert.equal(s.calls.length,1);});
