import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {PGlite} from '../work/sql-test/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
try{
 await db.exec(`create schema auth; create table auth.users(id uuid primary key,email_confirmed_at timestamptz);
 create role anon;create role authenticated;create role service_role bypassrls;
 create table public.organizations(id uuid primary key);
 create table public.organization_members(organization_id uuid,user_id uuid,role text,primary key(organization_id,user_id));`);
 await db.exec(readFileSync(new URL('../supabase/migrations/006_billing.sql',import.meta.url),'utf8'));
 const sql=readFileSync(new URL('../supabase/migrations/012_prepaid_test.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
 const [a,b,c,d,org]=Array.from({length:5},randomUUID);
 for(const u of [a,b,c,d])await db.query('insert into auth.users values($1,now())',[u]);
 await db.query('insert into organizations values($1)',[org]);
 for(const [u,role] of [[a,'owner'],[b,'member'],[c,'member'],[d,'member']])await db.query('insert into organization_members values($1,$2,$3)',[org,u,role]);
 const call=async(fn,args)=>(await db.query(`select public.${fn}(${args.map((_,i)=>'$'+(i+1)).join(',')}) v`,args)).rows[0].v;
 const w=await call('prepaid_test_open',[a,'business',org]);assert.equal(await call('prepaid_test_open',[a,'business',org]),w);
 await assert.rejects(call('prepaid_test_open',[b,'business',org]),/FORBIDDEN/);
 const personal=await call('prepaid_test_open',[b,'individual',null]);
 await call('prepaid_test_member',[a,w,b,true]);await call('prepaid_test_member',[a,w,c,true]);
 await assert.rejects(call('prepaid_test_member',[a,w,d,true]),/SEAT_LIMIT/);
 await assert.rejects(call('prepaid_test_member',[b,w,c,false]),/FORBIDDEN/);
 const lease=await call('billing_test_lock',[a]);
 const expiry=new Date(Date.now()+86400000).toISOString();
 await assert.rejects(call('prepaid_test_access',[a,w,randomUUID(),expiry]),/BUSY/);
 await call('prepaid_test_access',[a,w,lease.lock_token,expiry]);
 const state=async()=>(await db.query('select * from prepaid_test_wallets where id=$1',[w])).rows[0];
 assert.equal(Number((await state()).balance_cents),0);
 await assert.rejects(call('prepaid_test_reserve',[a,w,randomUUID(),1]),/INSUFFICIENT_CREDITS/);
 const order=randomUUID();
 await call('prepaid_test_order',[a,w,order,'credits',1000,'cus_a']);
 await call('prepaid_test_bind',[order,'cs_test_a']);
 await assert.rejects(call('prepaid_test_credit',[order,'cs_test_a','cus_b','pi_a',1000,false]),/CONFLICT/);
 await assert.rejects(call('prepaid_test_order',[a,w,order,'credits',2000,'cus_a']),/CONFLICT/);
 await Promise.all(Array.from({length:6},()=>call('prepaid_test_credit',[order,'cs_test_a','cus_a','pi_a',1000,false])));
 assert.equal(Number((await state()).balance_cents),1000);
 const attempts=Array.from({length:5},()=>randomUUID());
 const results=await Promise.allSettled(attempts.map(id=>call('prepaid_test_reserve',[b,w,id,300])));
 assert.equal(results.filter(r=>r.status==='fulfilled').length,3);
 assert.equal(Number((await state()).reserved_cents),900);
 await assert.rejects(call('prepaid_test_reserve',[b,personal,randomUUID(),100]),/SYNC_REQUIRED/);
 const id=attempts[results.findIndex(r=>r.status==='fulfilled')];
 await assert.rejects(call('prepaid_test_reserve',[b,w,id,300]),/DUPLICATE/);
 await assert.rejects(call('prepaid_test_settle',[id,1000001]),/CEILING_EXCEEDED/);
 assert.equal(Number((await state()).reserved_cents),900);
 assert.equal(await call('prepaid_test_settle',[id,100000]),30);
 assert.equal(await call('prepaid_test_settle',[id,100000]),30);
 await assert.rejects(call('prepaid_test_settle',[id,99999]),/CONFLICT/);
 assert.equal(Number((await state()).balance_cents),970);assert.equal(Number((await state()).reserved_cents),600);
 await call('prepaid_test_access',[a,w,lease.lock_token,expiry]);assert.equal(Number((await state()).balance_cents),970);
 await call('prepaid_test_access',[a,w,lease.lock_token,null]);
 await assert.rejects(call('prepaid_test_reserve',[a,w,randomUUID(),1]),/SUBSCRIPTION_REQUIRED/);
 await call('prepaid_test_access',[a,w,lease.lock_token,expiry]);
 await db.query('delete from organization_members where organization_id=$1 and user_id=$2',[org,b]);
 await assert.rejects(call('prepaid_test_reserve',[b,w,randomUUID(),1]),/FORBIDDEN/);
 await call('prepaid_test_credit',[order,'cs_test_a','cus_a','pi_a',1000,true]);
 await assert.rejects(call('prepaid_test_reserve',[a,w,randomUUID(),1]),/FROZEN/);
 await call('prepaid_test_credit',[order,'cs_test_a','cus_a','pi_a',1000,false]);assert.equal((await state()).frozen,true);
 assert.equal(Number((await state()).balance_cents),970);
 assert.equal(Number((await db.query('select sum(delta_cents) n from prepaid_test_ledger where wallet_id=$1',[w])).rows[0].n),970);
 for(const role of ['anon','authenticated']){
  await db.exec(`set role ${role}`);
  await assert.rejects(db.query('select * from prepaid_test_wallets'),/permission denied/);
  await assert.rejects(call('prepaid_test_credit',[order,'cs_test_a','cus_a','pi_a',1000,false]),/permission denied/);
  await assert.rejects(call('prepaid_test_settle',[id,0]),/permission denied/);
  await db.exec('reset role');
 }
 console.log('Prepaid SQL passed: replay, zero monthly credits, payment deduplication, shared atomic balances, 3 seats, cancellation, refunds, accounting and privileges.');
}finally{await db.close();}
