import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import * as audio from '../lib/transcription.ts';
const source=ts.transpileModule(readFileSync(new URL('../components/transcription-panel.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2023,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function harness({permissionError=false,deferred=false,enabled=false,post}={}){
 let expire;const deadlines=new Set();
 const states=[],refs=[],effects=[];let si=0,ri=0,ei=0;const cleanups=[];let stopped=0,unsubscribed=0;const instances=[];let resolveMedia;const media={getTracks:()=>[{stop:()=>stopped++}]};const events={};let authChange;
 class Recorder{static isTypeSupported(t){return t.includes('webm');}constructor(){instances.push(this);this.state='inactive';}start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['audio'],{type:'audio/webm'})});this.onstop?.();}}
 const jsx=(type,props)=>({type,props});
 const deps={'react':{useState:initial=>{const i=si++;if(!(i in states))states[i]=initial;return[states[i],v=>states[i]=typeof v==='function'?v(states[i]):v];},useRef:initial=>{const i=ri++;return refs[i]??(refs[i]={current:initial});},useEffect:(fn,ds)=>{const i=ei++;if(!effects[i]||ds.some((v,j)=>v!==effects[i][j])){cleanups[i]?.();effects[i]=ds;cleanups[i]=fn();}}},'react/jsx-runtime':{jsx,jsxs:jsx},'next/link':()=>null,'@/lib/supabase/client':{createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'a'}}}),onAuthStateChange:fn=>{authChange=fn;return{data:{subscription:{unsubscribe:()=>unsubscribed++}}};}}})},'@/lib/transcription':audio,'./assistant-panel':{downloadReport:()=>{}}};
 deps['./service-funding']={useServiceFunding:()=>({ready:true,headers:{},panel:null,refresh:()=>{}})};
 deps['./use-unsaved-work']={useUnsavedWork:()=>{}};
 const mod={exports:{}};new Function('require','module','exports','navigator','MediaRecorder','window','fetch','setTimeout','clearTimeout',source)(n=>deps[n],mod,mod.exports,{mediaDevices:{getUserMedia:()=>permissionError?Promise.reject(new DOMException('denied','NotAllowedError')):deferred?new Promise(r=>resolveMedia=r):Promise.resolve(media)}},Recorder,{addEventListener:(n,fn)=>events[n]=fn,removeEventListener:n=>delete events[n]},async(url,options)=>options?.method==='POST'?post(options):({ok:true,status:200,json:async()=>({enabled,message:'Teste'})}),fn=>{expire=fn;deadlines.add(fn);return fn;},fn=>deadlines.delete(fn));
 function render(){si=ri=ei=0;return mod.exports.TranscriptionPanel();}
 const nodes=tree=>!tree||typeof tree!=='object'?[]:[tree,...[tree.props?.children].flat(Infinity).flatMap(nodes)];
 const find=(tree,p)=>nodes(tree).find(p);
 return{render,find,states,deadlines,expire:()=>expire(),get stopped(){return stopped;},get unsubscribed(){return unsubscribed;},get recorder(){return instances.at(-1);},resolve:()=>resolveMedia(media),changeAccount:()=>authChange(),unmount:()=>cleanups.forEach(fn=>fn?.()),events};
}
test('recording needs consent, stays local, stops tracks and yields preview file',async()=>{const h=harness();try{let tree=h.render();await tick();tree=h.render();assert.equal(h.find(tree,n=>n.props?.children==='Gravar com microfone').props.disabled,true);h.find(tree,n=>n.props?.id==='audio-share-consent').props.onChange({target:{checked:true}});tree=h.render();h.find(tree,n=>n.props?.children==='Gravar com microfone').props.onClick();await tick();tree=h.render();assert.equal(h.recorder.state,'recording');h.find(tree,n=>n.props?.children==='Parar gravação').props.onClick();tree=h.render();assert.equal(h.recorder.state,'inactive');assert.ok(h.stopped>0);assert.equal(h.states[0].name,'gravacao.webm');assert.equal(h.find(tree,n=>n.props?.children==='Transcrever').props.disabled,true);}finally{h.unmount();}assert.equal(h.unsubscribed,1);});
test('microphone denial has upload fallback and permission resolved after unmount is stopped',async()=>{const denied=harness({permissionError:true});try{denied.render();await tick();let t=denied.render();denied.find(t,n=>n.props?.id==='audio-share-consent').props.onChange({target:{checked:true}});t=denied.render();denied.find(t,n=>n.props?.children==='Gravar com microfone').props.onClick();await tick();assert.match(denied.states[3],/Permissão do microfone recusada/);}finally{denied.unmount();}
const h=harness({deferred:true});h.render();await tick();let t=h.render();h.find(t,n=>n.props?.id==='audio-share-consent').props.onChange({target:{checked:true}});t=h.render();h.find(t,n=>n.props?.children==='Gravar com microfone').props.onClick();h.unmount();h.resolve();await tick();assert.ok(h.stopped>0);assert.equal(h.recorder,undefined);});

async function ready(h){h.render();await tick();let t=h.render();h.find(t,n=>n.props?.id==='audio-upload').props.onChange({target:{files:[new File(['audio'],'teste.mp3')],value:''}});t=h.render();h.find(t,n=>n.props?.id==='audio-share-consent').props.onChange({target:{checked:true}});return h.render();}
test('recovery is off by default and requires its own checkbox',async()=>{for(const optIn of [false,true]){let sent;const h=harness({enabled:true,post:async options=>{sent=options;return {ok:true,json:async()=>({text:'Texto'})};}});try{let t=await ready(h);if(optIn){h.find(t,n=>n.type==='input'&&n.props.type==='checkbox'&&n.props.id!=='audio-share-consent').props.onChange({target:{checked:true}});t=h.render();}h.find(t,n=>n.props?.children==='Transcrever').props.onClick();await tick();assert.equal(sent.headers['x-recovery-consent'],String(optIn));}finally{h.unmount();}}});
test('pending transcription shows indeterminate progress, prevents duplicates and reports completion',async()=>{
 let resolve,calls=0;const h=harness({enabled:true,post:()=>{calls++;return new Promise(r=>resolve=r);}});
 try{let t=await ready(h);const click=h.find(t,n=>n.props?.children==='Transcrever').props.onClick;click();click();t=h.render();assert.equal(calls,1);assert.ok(h.find(t,n=>n.type==='progress'));assert.equal(h.find(t,n=>n.props?.children==='A transcrever…').props.disabled,true);resolve({ok:true,json:async()=>({text:'Texto transcrito.'})});await tick();t=h.render();assert.equal(h.states[2],'Texto transcrito.');assert.equal(h.find(t,n=>n.type==='progress'),undefined);assert.equal(h.deadlines.size,0);}finally{h.unmount();}
});
for(const timeout of [false,true])test(timeout?'timeout preserves audio without retry':'stop waiting preserves audio and warns about processing',async()=>{
 let calls=0;const h=harness({enabled:true,post:({signal})=>{calls++;return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))));}});
 try{let t=await ready(h);h.find(t,n=>n.props?.children==='Transcrever').props.onClick();t=h.render();if(timeout)h.expire();else h.find(t,n=>n.props?.children==='Parar de aguardar').props.onClick();await tick();assert.match(h.states[3],timeout?/excedeu/:/Deixou de aguardar/);assert.match(h.states[3],/custos/);assert.equal(h.states[0].name,'teste.mp3');assert.equal(h.states[7],false);assert.equal(calls,1);assert.equal(h.deadlines.size,0);}finally{h.unmount();}
});
