import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
function load(file,deps={},env={}){const source=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2023,esModuleInterop:true}}).outputText;const m={exports:{}};new Function('require','module','exports','process',source)(n=>{if(!(n in deps))throw Error(n);return deps[n];},m,m.exports,{env:{AI_EXECUTION_ENABLED:'true',OPENAI_API_KEY:'fake',...env}});return m.exports;}
const audio=load('../lib/transcription.ts');const wav=Buffer.from('RIFF0000WAVEdata0000');const id='11111111-1111-4111-8111-111111111111';
function setup(options={}){const calls={provider:[],rpc:[],files:[],config:[]};const admin={rpc:async(name,args)=>{calls.rpc.push([name,args]);return {error:name==='assistant_begin'&&options.quota?{message:options.quota}:null};}};class OpenAI{constructor(config){calls.config.push(config);}audio={transcriptions:{create:async input=>{calls.provider.push(input);if(options.providerError)throw Error('SECRET provider body');return options.result??{text:'Texto transcrito.'};}}};}
const route=load('../app/api/transcription/route.ts',{'next/server':{NextResponse:{json:(data,init)=>Response.json(data,init)}},openai:{__esModule:true,default:OpenAI,toFile:async(bytes,name)=>{calls.files.push({bytes,name});return {name};}},'@/lib/supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user:options.noUser?null:{id}},error:null})}})},'@/lib/supabase/admin':{createAdminClient:()=>admin},'@/lib/billing-access':{paidAIAccessError:()=>options.blocked?'BILLING_TEST_ONLY':''},'@/lib/transcription':audio},options.env);
return {calls,route,post:(bytes=wav,headers={})=>route.POST(new Request('https://lic.test/api/transcription',{method:'POST',headers:{origin:'https://lic.test','x-request-id':id,'x-audio-consent':'true','x-audio-extension':'wav',...headers},body:bytes}))};}
test('audio validates supported containers, bounded bytes and output',()=>{audio.validateAudio(wav,'wav');audio.validateAudio(Buffer.from([0x1a,0x45,0xdf,0xa3]),'webm');audio.validateAudio(Buffer.from('ID3sample'),'mp3');audio.validateAudio(Buffer.from('0000ftypM4A '),'m4a');assert.throws(()=>audio.validateAudio(Buffer.from('<html>'),'wav'));assert.throws(()=>audio.validateAudio(Buffer.alloc(audio.MAX_AUDIO_BYTES+1),'mp3'));assert.throws(()=>audio.validateAudio(Buffer.alloc(0),'wav'));assert.throws(()=>audio.audioExtension('x.exe'));assert.throws(()=>audio.transcriptionText({text:' '}));assert.throws(()=>audio.transcriptionText({text:'x'.repeat(60001)}));});
test('CSRF, consent, login and paid guards reject without reading/transcribing audio',async()=>{for(const [options,headers,status] of [[{}, {origin:'https://evil.test'},403],[{}, {'x-audio-consent':'false'},400],[{noUser:true},{},401],[{blocked:true},{},403],[{env:{AI_EXECUTION_ENABLED:'false'}},{},503]]){const s=setup(options);assert.equal((await s.post(wav,headers)).status,status);assert.equal(s.calls.provider.length,0);assert.equal(s.calls.rpc.length,0);}});
test('oversized, disguised audio and invalid languages do not reserve quota or call provider',async()=>{for(const [bytes,headers] of [[Buffer.alloc(audio.MAX_AUDIO_BYTES+1),{}],[Buffer.from('<html>'),{}],[wav,{'x-audio-language':'arbitrary'}],[wav,{'content-length':String(audio.MAX_AUDIO_BYTES+1)}]]){const s=setup();assert.ok((await s.post(bytes,headers)).status>=400);assert.equal(s.calls.provider.length,0);assert.equal(s.calls.rpc.length,0);}});
test('quota blocks duplicates and concurrency before paid work',async()=>{for(const quota of ['BUSY','DUPLICATE','RATE_LIMITED']){const s=setup({quota});assert.equal((await s.post()).status,429);assert.equal(s.calls.provider.length,0);}});
test('transcription uses generic filename, explicit language, no retry and no stored audio',async()=>{const s=setup();const r=await s.post(wav,{'x-audio-language':'pt'});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).text,'Texto transcrito.');assert.equal(s.calls.files[0].name,'audio.wav');assert.equal(s.calls.provider[0].language,'pt');assert.equal(s.calls.config[0].maxRetries,0);assert.deepEqual(s.calls.rpc.map(c=>c[0]),['assistant_begin','assistant_finish']);assert.equal(s.calls.rpc[1][1].p_success,true);});
test('failures release request and never expose provider details or invent text',async()=>{for(const options of [{providerError:true},{result:{text:''}}]){const s=setup(options);const r=await s.post();assert.equal(r.status,502);assert.doesNotMatch(JSON.stringify(await r.json()),/SECRET/);assert.equal(s.calls.rpc.at(-1)[1].p_success,false);assert.equal(s.calls.provider.length,1);}});
test('availability never enables sandbox paid calls',async()=>{const s=setup({blocked:true});const r=await s.route.GET();assert.equal((await r.json()).enabled,false);assert.equal(s.calls.provider.length,0);});
