"use client";
import {useState,useRef,useEffect} from 'react';
import {blankRecord,currentRecords,locateQuote,potentialContradictions,recordKinds,temporalStatus,readCaseRecord,type CaseRecord} from '@/lib/case-workspace';
import type {LibraryEntry} from '@/lib/library';
import {useUnsavedWork} from './use-unsaved-work';
import {SourceImport} from './source-import';
export function CaseWorkspace({entries,disabled,onSave,onDirty}:{entries:LibraryEntry[];disabled:boolean;onSave:(title:string,record:CaseRecord,revision:string|undefined,id:string)=>Promise<void>;onDirty?:(dirty:boolean)=>void}){
 const [record,setRecord]=useState(blankRecord),[title,setTitle]=useState(''),[revision,setRevision]=useState<string>(),[message,setMessage]=useState(''),[date,setDate]=useState(''),[query,setQuery]=useState(''),[quote,setQuote]=useState(''),[claim,setClaim]=useState(''),[source,setSource]=useState('');
 const [saving,setSaving]=useState(false),saveLock=useRef(false),alive=useRef(true),saveAttempt=useRef<{key:string;id:string}|null>(null),formDetails=useRef<HTMLDetailsElement>(null);
 const blocked=disabled||saving;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{onDirty?.(!!record.text||!!title);return()=>onDirty?.(false);},[record.text,title,onDirty]);
 useUnsavedWork(!!record.text||!!title);
 async function persist(name:string,value:CaseRecord,prior?:string){
  if(saveLock.current)return false;saveLock.current=true;setSaving(true);
  const key=JSON.stringify([name,value,prior]);if(saveAttempt.current?.key!==key)saveAttempt.current={key,id:crypto.randomUUID()};
  try{await onSave(name,value,prior,saveAttempt.current.id);if(!alive.current)return false;saveAttempt.current=null;return true;}
  finally{saveLock.current=false;if(alive.current)setSaving(false);}
 }
 const records=currentRecords(entries),sources=records.filter(e=>e.record.kind==='source'||e.record.kind==='document');
 const selected=sources.find(e=>e.id===source),located=selected?locateQuote(selected.record.text,quote):null;
 const conflict=potentialContradictions(records);
 const visible=records.filter(e=>(!query||`${e.title} ${e.record.text} ${e.record.reference}`.toLocaleLowerCase('pt-PT').includes(query.toLocaleLowerCase('pt-PT')))&&(!date||e.record.kind!=='source'||temporalStatus(e.record,date)!=='outside')).sort((a,b)=>(a.record.date||'9999').localeCompare(b.record.date||'9999'));
 function update<K extends keyof CaseRecord>(key:K,value:CaseRecord[K]){setRecord(r=>({...r,[key]:value}));}
 return <section className="case-workspace"><h3>Espaço de trabalho do dossier</h3><p>Memória apenas deste assunto. Fontes, factos e provas não são enviados à IA automaticamente. As versões e ligações mantêm as permissões do dossier.</p>
 <div className="workbench-grid"><label>Pesquisar conteúdo<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={200}/></label><label>Fontes na data (intervalos declarados)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>
 {conflict.length>0&&<p role="status">{conflict.length} grupo(s) com textos diferentes para a mesma referência e data. São potenciais divergências textuais, não contradições jurídicas demonstradas.</p>}
 {conflict.map((group,i)=><details key={i}><summary>Rever divergência: {group[0].record.reference}</summary>{group.map(r=><p key={r.id}><a href={'#case-'+r.id}>{r.record.text.slice(0,220)}</a></p>)}</details>)}
 <div className="case-timeline">{visible.map(e=><article className="card" id={'case-'+e.id} key={e.id}><small>{recordKinds[e.record.kind]} · {e.record.date||'Data por indicar'} · {e.record.status==='pending'?'Por rever':e.record.status==='done'?'Concluído pelo utilizador':'Revisto pelo utilizador'}</small><h4>{e.title}</h4><p>{e.record.reference} {e.record.jurisdiction}</p>{date&&e.record.kind==='source'&&<p>{temporalStatus(e.record,date)==='declared-in-range'?'Dentro do intervalo revisto pelo utilizador; confirmar aplicabilidade.':'Vigência por confirmar.'}</p>}<details><summary>Ler conteúdo e relações</summary><pre className="readable-pre">{e.record.text}</pre>{e.record.url&&<a href={e.record.url} target="_blank" rel="noopener noreferrer">Abrir original</a>}{e.record.related.map(id=><p key={id}><a href={'#'+id}>{entries.find(x=>x.id===id)?.title||'Referência não disponível'}</a></p>)}</details><button disabled={blocked} className="btn btn-secondary" onClick={()=>{if(record.text&&!confirm('Substituir o rascunho?'))return;setRecord(e.record);setTitle(e.title);setRevision(e.id);if(formDetails.current){formDetails.current.open=true;formDetails.current.scrollIntoView({behavior:'smooth',block:'center'});}}}>Rever / actualizar estado</button></article>)}</div>
 <details ref={formDetails}><summary>Adicionar fonte, facto, prova, interveniente ou tarefa</summary><form onSubmit={async e=>{e.preventDefault();if(!readCaseRecord(JSON.stringify(record))){setMessage('Verifique texto, datas e endereço.');return;}try{if(!await persist(title,record,revision))return;setRecord(blankRecord());setTitle('');setRevision(undefined);setMessage('Versão guardada.');}catch{setMessage('Não foi possível guardar. O rascunho foi preservado.');}}}><fieldset disabled={blocked}><legend>{revision?'Nova versão; o original é conservado':'Novo registo estruturado'}</legend><label>Tipo<select value={record.kind} onChange={e=>update('kind',e.target.value as CaseRecord['kind'])}>{Object.entries(recordKinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Título<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Conteúdo autorizado / excerto original<textarea required rows={8} maxLength={60000} value={record.text} onChange={e=>update('text',e.target.value)}/></label><label>Referência estável (artigo, processo, prova ou tarefa)<input maxLength={500} value={record.reference} onChange={e=>update('reference',e.target.value)}/></label><div className="workbench-grid"><label>Data / início de vigência<input type="date" value={record.date} onChange={e=>update('date',e.target.value)}/></label><label>Fim de vigência, se conhecido<input type="date" value={record.until} onChange={e=>update('until',e.target.value)}/></label></div><label>Jurisdição<input maxLength={80} value={record.jurisdiction} onChange={e=>update('jurisdiction',e.target.value)}/></label><label>Endereço original<input type="url" maxLength={2000} value={record.url} onChange={e=>update('url',e.target.value)}/></label>{record.kind==='source'&&<SourceImport url={record.url} disabled={disabled} onImport={(text,reference)=>setRecord(r=>({...r,text,reference,status:'pending'}))}/>}<label>Estado (declaração sua)<select value={record.status} onChange={e=>update('status',e.target.value as CaseRecord['status'])}><option value="pending">Por rever</option><option value="reviewed">Revisto</option><option value="done">Concluído</option></select></label><label>Ligar a provas / registos (máximo 30)<select multiple value={record.related} onChange={e=>update('related',Array.from(e.target.selectedOptions,o=>o.value).slice(0,30))}>{entries.map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label><button className="btn btn-primary">Guardar registo</button></fieldset></form></details>
 <details><summary>Conferir uma afirmação com o original</summary><p>A conferência abaixo localiza o excerto no texto guardado. Não prova que a afirmação decorra dele. Consulte o contexto, excepções, data e a fonte original.</p><label>Afirmação a conferir<textarea maxLength={3000} value={claim} onChange={e=>setClaim(e.target.value)}/></label><label>Fonte / documento<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Seleccione</option>{sources.map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label><label>Excerto literal (mínimo 12 caracteres)<textarea maxLength={4000} value={quote} onChange={e=>setQuote(e.target.value)}/></label>{quote&&<p role="status">{located?`Excerto localizado${located.multiple?' em várias passagens':''}. Fundamentação da afirmação ainda por rever.`:'Excerto não localizado: não o apresente como citação verificada.'}</p>}{located&&<blockquote>{located.context}</blockquote>}<button disabled={blocked||!claim.trim()||!selected} className="btn btn-secondary" onClick={async()=>{const r={...blankRecord(),kind:'evidence' as const,text:`Afirmação: ${claim}\nExcerto: ${quote}\nConferência literal: ${located?'localizado':'não localizado'}\nFundamentação semântica: por rever`,related:[source],url:selected!.record.url};try{if(!await persist(('Conferência — '+claim).slice(0,160),r))return;setMessage('Conferência guardada, por rever.');}catch{setMessage('Não foi possível guardar.');}}}>Guardar conferência pendente</button></details>
 <p role="status">{saving?'A guardar…':message}</p></section>;
}
