'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
type Team={id:string;name:string;members:{id:string;email:string}[]};
type Grant={organization_id:string;member_id:string;active:boolean;access_role:'viewer'|'editor'};
export function DossierSharing({id}:{id:string}){
 const [teams,setTeams]=useState<Team[]>([]),[grants,setGrants]=useState<Grant[]>([]),[self,setSelf]=useState(''),[team,setTeam]=useState(''),[member,setMember]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const [role,setRole]=useState<'viewer'|'editor'>('editor');
 const lock=useRef(false),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function read(){const r=await fetch('/api/library?access='+encodeURIComponent(id));const data=await r.json();if(!r.ok)throw Error(data.error);if(alive.current){setTeams(data.teams);setGrants(data.grants);setSelf(data.userId);setLoaded(true);}}
 async function act(change?:{organizationId:string;memberId:string;allow:boolean;role:'viewer'|'editor'}){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{if(change){const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'share',dossierId:id,...change})});const data=await r.json();if(!r.ok)throw Error(data.error);}await read();if(alive.current&&change)setMessage(change.allow?'Permissões actualizadas.':'Acesso revogado. Cópias já exportadas não podem ser retiradas.');}catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'Não foi possível actualizar os acessos.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
 return <section><h3>Partilhar com a equipa</h3><p>Escolha leitura ou edição. Editores podem acrescentar notas e guardar revisões sem apagar os originais. Só o titular gere acessos e elimina registos. A partilha abrange todas as notas e versões, incluindo futuras. Confirme que tem autorização para divulgar o conteúdo. Revogar acesso não apaga cópias já exportadas.</p>
 <button type="button" disabled={busy} className="btn btn-secondary" onClick={()=>void act()}>Consultar acessos e membros</button>
 {loaded&&<><label>Equipa<select disabled={busy} value={team} onChange={e=>{setTeam(e.target.value);setMember('');}}><option value="">Seleccione</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Membro<select disabled={busy||!team} value={member} onChange={e=>setMember(e.target.value)}><option value="">Seleccione</option>{teams.find(t=>t.id===team)?.members.filter(m=>m.id!==self).map(m=><option key={m.id} value={m.id}>{m.email}</option>)}</select></label><label>Permissão<select disabled={busy} value={role} onChange={e=>setRole(e.target.value as 'viewer'|'editor')}><option value="editor">Edição — notas e novas versões</option><option value="viewer">Apenas leitura</option></select></label><button type="button" disabled={busy||!team||!member} className="btn btn-secondary" onClick={()=>{const recipient=teams.find(t=>t.id===team)?.members.find(m=>m.id===member);if(recipient&&confirm(`Dar a ${recipient.email} ${role==='editor'?'acesso de edição, leitura e exportação':'acesso de leitura e exportação'} a todo este dossier, incluindo futuras notas?`))void act({organizationId:team,memberId:member,allow:true,role});}}>Guardar permissão</button>
 {grants.length===0&&<p>Nenhum acesso partilhado.</p>}{grants.map(g=><p key={g.organization_id+g.member_id}>{teams.find(t=>t.id===g.organization_id)?.name||'Equipa anterior'} · {teams.find(t=>t.id===g.organization_id)?.members.find(m=>m.id===g.member_id)?.email||g.member_id} · {g.active?(g.access_role==='editor'?'Edição':'Leitura'):'Inactivo'} <button type="button" disabled={busy} onClick={()=>void act({organizationId:g.organization_id,memberId:g.member_id,allow:false,role:g.access_role})}>Revogar</button></p>)}<p><Link href="/team">Gerir membros da equipa</Link></p></>}
 <p role="status">{message}</p>{message&&<Link href="/setup/services">Configuração de armazenamento e partilha</Link>}</section>;
}
