"use client";
import {useEffect,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
type Item={id:string;filename:string;organization_id:string};
export function DossierDocuments({onAttach,disabled}:{onAttach:(item:Item)=>void;disabled:boolean}){
 const [items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(false),[confirmed,setConfirmed]=useState(false);
 const epoch=useRef(0);
 useEffect(()=>{const client=createClient();const subscription=client?.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'||event==='SIGNED_IN'){epoch.current++;setItems([]);setSelected('');setConfirmed(false);setLoading(false);}});return()=>{epoch.current++;subscription?.data.subscription.unsubscribe();};},[]);
 async function load(){const v=epoch.current;setLoading(true);setStatus('');try{const client=createClient();if(!client)throw Error();const r=await client.from('contracts').select('id,filename,organization_id').eq('status','uploaded').order('created_at',{ascending:false}).limit(100);if(v!==epoch.current)return;if(r.error)throw Error();setItems(r.data??[]);setStatus(r.data?.length?'Seleccione o documento a referenciar.':'Não há documentos disponíveis nas suas empresas.');}catch{if(v===epoch.current)setStatus('Não foi possível carregar os documentos. Confirme a sessão e tente novamente.');}finally{if(v===epoch.current)setLoading(false);}}
 return <details className="dossier-documents"><summary>Ligar um documento ao dossier</summary><p>Guarda uma referência, não uma cópia. O ficheiro continua protegido pelas permissões da empresa.</p><button type="button" className="btn btn-secondary" disabled={disabled||loading} onClick={()=>void load()}>{loading?'A carregar…':'Carregar documentos acessíveis'}</button><label>Documento<select disabled={disabled||loading} value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false);}}><option value="">Seleccione</option>{items.map(item=><option key={item.id} value={item.id}>{item.filename}</option>)}</select></label><label className="analysis-consent"><input type="checkbox" checked={confirmed} disabled={disabled} onChange={e=>setConfirmed(e.target.checked)}/>Autorizo guardar o nome e a referência do documento neste dossier, visíveis a todos os seus membros. Isto não lhes dá acesso ao ficheiro.</label><button type="button" className="btn btn-secondary" disabled={disabled||!selected||!confirmed} onClick={()=>{const item=items.find(v=>v.id===selected);if(item){onAttach(item);setConfirmed(false);}}}>Guardar referência no dossier</button>{status&&<p role="status">{status}</p>}</details>;
}
