"use client";
import {useEffect,useState} from 'react';
import {parsePlaybook,applyPlaybook,acceptPlaybookFinding,type Playbook,type PlaybookFinding} from '@/lib/playbook';
export function PlaybookReview({text,onApply}:{text:string;onApply:(value:string)=>void}){
 const [book,setBook]=useState<Playbook>({version:1,name:'Manual de revisão do cliente',rules:[]}),[findings,setFindings]=useState<PlaybookFinding[]>([]),[message,setMessage]=useState('');
 useEffect(()=>{setFindings([]);},[book,text]);
 return <details className="playbook"><summary>Rever segundo as regras do cliente</summary><p>Pesquisa literal, sensível a maiúsculas. Define posições preferidas, expressões proibidas e textos obrigatórios. Uma regra interna não prevalece sobre a lei; cada alteração exige aprovação sua. Não interpreta equivalências jurídicas.</p>
 <label>Importar regras JSON (até 64 KB)<input type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>64000)throw Error('Ficheiro demasiado grande.');setBook(parsePlaybook(JSON.parse(await f.text())));setFindings([]);setMessage('Regras carregadas.');}catch(e){setMessage(e instanceof Error?e.message:'Ficheiro inválido.');}}}/></label>
 <label>Nome do manual<input maxLength={160} value={book.name} onChange={e=>setBook({...book,name:e.target.value})}/></label>
 {book.rules.map((r,i)=><fieldset key={r.id}><legend>Regra {i+1}</legend><label>Tipo<select value={r.kind} onChange={e=>setBook({...book,rules:book.rules.map((x,j)=>j===i?{...x,kind:e.target.value as typeof r.kind}:x)})}><option value="required">Expressão obrigatória</option><option value="prohibited">Expressão proibida</option><option value="preferred">Redacção preferida</option></select></label>{(['phrase','alternative','reason'] as const).map((key,n)=><label key={key}>{['Expressão exacta','Alternativa aceitável','Justificação / limites'][n]}<textarea rows={2} maxLength={4000} value={r[key]} onChange={e=>setBook({...book,rules:book.rules.map((x,j)=>j===i?{...x,[key]:e.target.value}:x)})}/></label>)}<button type="button" onClick={()=>setBook({...book,rules:book.rules.filter((_,j)=>j!==i)})}>Retirar regra</button></fieldset>)}
 <button type="button" className="btn btn-secondary" disabled={book.rules.length>=100} onClick={()=>setBook({...book,rules:[...book.rules,{id:crypto.randomUUID(),kind:'preferred',phrase:'',alternative:'',reason:''}]})}>Adicionar regra</button>
 <button type="button" className="btn btn-secondary" onClick={()=>{try{parsePlaybook(book);const url=URL.createObjectURL(new Blob([JSON.stringify(book,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='manual-revisao-lic.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage((e as Error).message);}}}>Exportar regras</button>
 <button type="button" className="btn btn-primary" disabled={!text.trim()} onClick={()=>{try{const found=applyPlaybook(text,book);setFindings(found);setMessage(`${found.length} ocorrências ou ausências. A ausência de resultados não comprova conformidade.`);}catch(e){setMessage((e as Error).message);}}}>Executar revisão literal</button><p role="status">{message}</p>
 {findings.map((f,i)=><article className="card" key={f.rule.id+'-'+i}><h4>{f.state==='missing'?'Expressão obrigatória não encontrada':'Expressão a rever'} · {f.rule.phrase}</h4><p>{f.rule.reason}</p><div className="legal-versions"><blockquote>{f.original||'Cláusula por localizar / inserir manualmente'}</blockquote><blockquote>{f.proposal||'Sem alternativa definida'}</blockquote></div><button type="button" disabled={!f.proposal||f.state==='missing'} onClick={()=>{try{onApply(acceptPlaybookFinding(text,f));setFindings([]);setMessage('Alteração aprovada e aplicada ao rascunho. Volte a executar para rever as restantes.');}catch(e){setMessage((e as Error).message);}}}>Aprovar apenas esta alteração</button></article>)}
 </details>;
}
