"use client";
import {useEffect,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {documentError,type Contract} from '@/lib/documents';
/** Download through authenticated Storage RLS, never a public share URL. */
export function PrivatePdfPreview({contract}:{contract:Contract}){
 const [url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState('1'),[shownPage,setShownPage]=useState(1);
 const resource=useRef(''),epoch=useRef(0);
 function release(){epoch.current++;if(resource.current)URL.revokeObjectURL(resource.current);resource.current='';setUrl('');setBusy(false);setPage('1');setShownPage(1);}
 useEffect(()=>{const client=createClient();const {data}=client?.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'||event==='SIGNED_IN'){release();setError('');}})??{data:undefined};return()=>{epoch.current++;if(resource.current)URL.revokeObjectURL(resource.current);data?.subscription.unsubscribe();};},[contract.id]);
 async function open(){if(busy)return;const version=++epoch.current;setBusy(true);setError('');try{const client=createClient();if(!client)throw Error();const result=await client.storage.from('contracts').download(contract.storage_path);if(result.error)throw result.error;if(version!==epoch.current)return;if(result.data.size>20*1024*1024||new TextDecoder().decode(await result.data.slice(0,5).arrayBuffer())!=='%PDF-')throw Error('INVALID_FILE');if(version!==epoch.current)return;if(resource.current)URL.revokeObjectURL(resource.current);resource.current=URL.createObjectURL(new Blob([result.data],{type:'application/pdf'}));setUrl(resource.current);}catch(e){if(version===epoch.current)setError(documentError(e));}finally{if(version===epoch.current)setBusy(false);}}
 if(contract.mime_type!=='application/pdf')return null;
 return <section className="private-pdf"><h3>Conferir o documento original</h3><p>A pré-visualização não chama IA nem publica o ficheiro. O número abaixo é a página física do PDF, que pode diferir da numeração impressa.</p>{!url?<button className="btn btn-secondary" disabled={busy} onClick={()=>void open()}>{busy?'A abrir PDF…':'Abrir PDF nesta página'}</button>:<><form className="workspace-toolbar" onSubmit={e=>{e.preventDefault();const n=Number(page);if(Number.isInteger(n)&&n>=1&&n<=10000)setShownPage(n);}}><label htmlFor={'pdf-page-'+contract.id}>Página</label><input id={'pdf-page-'+contract.id} type="number" min={1} max={10000} required value={page} onChange={e=>setPage(e.target.value)}/><button className="btn btn-secondary">Ir para página</button><button type="button" className="btn btn-secondary" onClick={release}>Fechar PDF</button></form><iframe key={shownPage} sandbox="allow-same-origin" title={`Documento original: ${contract.filename}, página ${shownPage}`} src={url+'#page='+shownPage} className="pdf-frame"/><p className="assistant-small">Se o navegador não apresentar o PDF, use «Descarregar documento». Esta vista não extrai texto nem certifica a leitura de digitalizações.</p></>}{error&&<p role="alert">{error}</p>}</section>;
}
