'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {AppShell} from './app-shell';
import {useUnsavedWork} from './use-unsaved-work';
import {createClient} from '@/lib/supabase/client';
import {importWord,reviseImportedWord,type ImportedWord} from '@/lib/word-import';
import {trackedWord} from '@/lib/word-review';
import {qualityReport,reviewCriteria,type ReviewScore} from '@/lib/quality-review';
import type {Dossier} from '@/lib/library';
function download(data:Blob,name:string){const url=URL.createObjectURL(data),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function QualityWorkbench({mode}:{mode:'word'|'evaluation'}){
 const [original,setOriginal]=useState(''),[answer,setAnswer]=useState(''),[reviewer,setReviewer]=useState(''),[caseName,setCaseName]=useState(''),[model,setModel]=useState(''),[notes,setNotes]=useState(''),[seconds,setSeconds]=useState(''),[cost,setCost]=useState(''),[message,setMessage]=useState('');
 const [scores,setScores]=useState<ReviewScore[]>(reviewCriteria.map(()=>'pending'));
 const [dossiers,setDossiers]=useState<Dossier[]>([]),[dossier,setDossier]=useState(''),[busy,setBusy]=useState(false);
 const [imported,setImported]=useState<ImportedWord|null>(null),[fileName,setFileName]=useState('');
 const epoch=useRef(0),lock=useRef(false),upload=useRef(0);
 useUnsavedWork(Boolean(original||answer||notes));
 useEffect(()=>{const client=createClient();const subscription=client?.auth.onAuthStateChange((event)=>{if(event!=='SIGNED_OUT'&&event!=='SIGNED_IN')return;epoch.current++;upload.current++;setImported(null);setFileName('');setOriginal('');setAnswer('');setReviewer('');setCaseName('');setModel('');setNotes('');setSeconds('');setCost('');setMessage('');setDossiers([]);setDossier('');setScores(reviewCriteria.map(()=>'pending'));});return()=>{epoch.current++;subscription?.data.subscription.unsubscribe();};},[]);
 async function readFile(file:File){if((original||answer)&&!confirm('Substituir os textos actuais pelo ficheiro escolhido?'))return;const version=epoch.current,attempt=++upload.current;setBusy(true);setMessage('A importar localmente…');try{if(!file.name.toLowerCase().endsWith('.docx')||file.size>5*1024*1024)throw Error('Escolha um DOCX até 5 MB.');const data=await importWord(new Uint8Array(await file.arrayBuffer()));if(version!==epoch.current||attempt!==upload.current)return;setImported(data);setFileName(file.name);setOriginal(data.text);setAnswer(data.text);setMessage('DOCX importado localmente. Altere a proposta e exporte para rever no Word.');}catch(e){if(version===epoch.current&&attempt===upload.current)setMessage(e instanceof Error?e.message:'Não foi possível importar.');}finally{if(attempt===upload.current)setBusy(false);}}
 function report(){return qualityReport({caseName,reviewer,model,answer,notes,scores,seconds,cost});}
 async function save(loadOnly=false){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');const version=epoch.current;try{const response=await fetch('/api/library',loadOnly?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',id:crypto.randomUUID(),dossierId:dossier,title:('Avaliação — '+caseName).slice(0,160),body:report(),sources:[]})});const data=await response.json();if(version!==epoch.current)return;if(!response.ok)throw Error(data.error);if(loadOnly){setDossiers(data.dossiers.filter((d:Dossier)=>d.kind==='dossier'&&d.canEdit!==false));setMessage('Seleccione um dossier. Se não existir, crie-o primeiro noutra página após exportar o rascunho.');}else setMessage('Avaliação guardada no dossier. Quem tiver acesso partilhado pode consultá-la.');}catch(e){if(version===epoch.current)setMessage(e instanceof Error?e.message:'Não foi possível guardar.');}finally{lock.current=false;setBusy(false);}}
 return <AppShell><Link href="/services">Serviços jurídicos</Link><h1>{mode==='word'?'Revisão Word — alterações controladas':'Avaliação humana de respostas'}</h1><section className="card team-panel">
 <p>{mode==='word'?'Cole os textos ou importe um DOCX simples. Na importação preservamos os estilos e a estrutura original; a proposta de cada parágrafo usa a formatação do primeiro trecho. Não suportamos tabelas, imagens no corpo, campos ou revisões existentes. Cabeçalhos e rodapés são conservados, mas não são revistos aqui. Não é um suplemento do Word.':'Avalie uma resposta existente. Os critérios começam por avaliar: nada é aprovado pela IA. A identidade e as qualificações do revisor não são verificadas pela plataforma.'}</p>
 <p>Sem chamadas à IA e sem custos de geração. O rascunho fica apenas nesta página até exportar{mode==='evaluation'?' ou guardar expressamente no dossier':''}. Sair pode perder o trabalho.</p>
 {mode==='word'&&<section><label>Importar DOCX (local, até 5 MB)<input type="file" accept=".docx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void readFile(file);}}/></label>{imported&&<><p>Ficheiro: {fileName}. Mantenha o número de parágrafos para preservar a estrutura. Nada é enviado para servidores ou IA.</p><button type="button" disabled={busy} onClick={()=>{if(confirm('Descartar a formatação do ficheiro e continuar apenas com os textos?')){setImported(null);setFileName('');}}}>Continuar só com texto simples</button></>}</section>}
 <form onSubmit={e=>{e.preventDefault();setMessage('');try{if(mode==='word'){const bytes=imported?reviseImportedWord(imported,answer,reviewer):trackedWord(original,answer,reviewer);download(new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),'revisao-lic.docx');}else download(new Blob([report()],{type:'text/plain;charset=utf-8'}),'avaliacao-lic.txt');setMessage('Exportação preparada. Confirme o ficheiro nas transferências.');}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível exportar.');}}}>
 <label>Nome do revisor<input required maxLength={120} value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label>
 {mode==='word'?<label>Texto original<textarea required readOnly={Boolean(imported)} rows={10} maxLength={60000} value={original} onChange={e=>setOriginal(e.target.value)}/></label>:<><label>Caso / pergunta avaliada<input required maxLength={200} value={caseName} onChange={e=>setCaseName(e.target.value)}/></label><label>Modelo e versão (se conhecidos)<input maxLength={200} value={model} onChange={e=>setModel(e.target.value)}/></label></>}
 <label>{mode==='word'?'Texto proposto':'Resposta a avaliar'}<textarea required rows={10} maxLength={60000} value={answer} onChange={e=>setAnswer(e.target.value)}/></label>
 {mode==='evaluation'&&<><fieldset><legend>Revisão manual</legend>{reviewCriteria.map((criterion,i)=><label key={criterion}>{criterion}<select value={scores[i]} onChange={e=>setScores(scores.map((s,j)=>i===j?e.target.value as ReviewScore:s))}><option value="pending">Por avaliar</option><option value="pass">Conforme</option><option value="fail">Não conforme</option><option value="na">Não aplicável — justificar</option></select></label>)}</fieldset><label>Evidência, URLs, erros e justificações<textarea maxLength={12000} rows={6} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Tempo medido (segundos; opcional)<input inputMode="decimal" maxLength={15} value={seconds} onChange={e=>setSeconds(e.target.value)}/></label><label>Custo confirmado (EUR; opcional)<input inputMode="decimal" maxLength={15} value={cost} onChange={e=>setCost(e.target.value)}/></label></>}
 <button disabled={busy} className="btn btn-primary">{mode==='word'?'Exportar Word com alterações':'Exportar ficha de avaliação'}</button></form>
 {mode==='evaluation'&&<section><h2>Conservar avaliação</h2><button disabled={busy} className="btn btn-secondary" onClick={()=>void save(true)}>Carregar os meus dossiers</button><label>Dossier privado<select disabled={busy} value={dossier} onChange={e=>setDossier(e.target.value)}><option value="">Seleccione</option>{dossiers.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><button disabled={busy||!dossier} className="btn btn-secondary" onClick={()=>void save()}>Guardar avaliação no dossier</button><p>Guardar não comprova revisão por advogado nem aprova o lançamento. A avaliação fica acessível ao titular e aos membros com quem este partilhou o dossier.</p></section>}
 <p role="status">{message}</p></section></AppShell>;
}
