"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { AppShell } from './app-shell';
import { createClient } from '@/lib/supabase/client';
import { compareReports, exportDossier, type Dossier, type LibraryEntry, type LibrarySource, sourceEvidence } from '@/lib/library';
import { readClause } from '@/lib/clauses';
import { safeSourceUrl } from '@/lib/legal-research';
import { downloadReport } from './assistant-panel';
import { SourceEvidence } from './source-evidence';
import { useUnsavedWork } from './use-unsaved-work';
export function ResearchLibrary({kind}:{kind:'dossier'|'watch'|'clause'}) {
 const [dossiers,setDossiers]=useState<Dossier[]>([]),[entries,setEntries]=useState<LibraryEntry[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[noteTitle,setNoteTitle]=useState(''),[body,setBody]=useState(''),[sources,setSources]=useState<LibrarySource[]>([]);
 const [approved,setApproved]=useState(false),[usage,setUsage]=useState('');
 const [filter,setFilter]=useState('');
 useUnsavedWork(Boolean(body||noteTitle||sources.length));
 const epoch=useRef(0),lock=useRef(false);
 async function load(id='') { const version=++epoch.current; setBusy(true); try { const r=await fetch('/api/library'+(id?'?id='+encodeURIComponent(id):'')); const d=await r.json(); if(version!==epoch.current)return; if(!r.ok)throw Error(d.error);setDossiers(d.dossiers);setEntries(d.entries??[]);setSelected(id);setError(''); }catch(e){if(version===epoch.current)setError(e instanceof Error?e.message:'Não foi possível carregar.');}finally{if(version===epoch.current)setBusy(false);} }
 useEffect(()=>{ void load(); const client=createClient(); const subscription=client?.auth.onAuthStateChange(()=>{epoch.current++;setFilter('');setApproved(false);setUsage('');setEntries([]);setDossiers([]);setSelected('');setBody('');setTitle('');setDescription('');setNoteTitle('');setSources([]);void load();});return()=>{epoch.current++;subscription?.data.subscription.unsubscribe();};},[]);
 async function mutate(payload:object,next=selected) { if(lock.current)return;lock.current=true;setBusy(true);setError('');const version=epoch.current;try{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(version!==epoch.current)return;if(!r.ok)throw Error(d.error);setBody('');setApproved(false);setUsage('');setNoteTitle('');setSources([]);await load(next);}catch(e){if(version===epoch.current)setError(e instanceof Error?e.message:'Falha ao guardar.');}finally{lock.current=false;setBusy(false);} }
 const current=dossiers.find(d=>d.id===selected); const diff=kind==='watch'&&entries.length>=2?compareReports(entries[1].body,entries[0].body):null;
 return <AppShell><h1>{kind==='watch'?'Alertas legislativos — consulta manual' :kind==='clause'?'Biblioteca pessoal de cláusulas':'Dossiers de pesquisa'}</h1><p>Área pessoal. Guarde apenas conteúdo que tem autorização para conservar. Não existe envio automático para a IA.</p>{kind==='watch'&&<p>Sem monitorização contínua ou e-mails. <Link href="/services/watch">Consultar alterações com IA</Link>: indique o tema e o período, reveja as fontes e guarde o relatório abaixo. A IA paga permanece bloqueada nesta fase.</p>}
 {error&&<p role="alert">{error} <Link href="/login">Entrar</Link> · <Link href="/setup/services">Configurar armazenamento</Link></p>}
 {kind==='clause'&&<p>Cada cláusula reúne versões guardadas separadamente. A aprovação é uma declaração sua, não uma validação jurídica automática. As versões podem ser eliminadas; isto não é um arquivo de auditoria imutável.</p>}
 <section className="card team-panel"><h2>{kind==='watch'?'Novo tema':kind==='clause'?'Nova cláusula':'Novo dossier'}</h2><form onSubmit={e=>{e.preventDefault();const id=crypto.randomUUID();void mutate({action:'create',id,kind,title,description},id);}}><label>Título<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Descrição / período de interesse<textarea maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>Criar</button></form></section>
 {kind==='clause'&&<label>Pesquisar título ou contexto<input maxLength={160} value={filter} onChange={e=>setFilter(e.target.value)}/></label>}
 <label>Escolher<select disabled={busy} value={selected} onChange={e=>{if(body&&!confirm('Descartar o rascunho não guardado?'))return;setBody('');setUsage('');setApproved(false);setNoteTitle('');setSources([]);void load(e.target.value);}}><option value="">Seleccione</option>{dossiers.filter(d=>d.kind===kind&&(!filter||`${d.title} ${d.description}`.toLocaleLowerCase('pt-PT').includes(filter.toLocaleLowerCase('pt-PT')))).map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
 {current&&<section className="card team-panel"><h2>{current.title}</h2><p>{current.description}</p><button className="btn btn-secondary" onClick={()=>downloadReport(exportDossier(current,entries),'dossier-lic.txt')}>{kind==='clause'?'Exportar todas as versões':'Exportar dossier'}</button><button className="btn btn-secondary" disabled={busy} onClick={()=>{if(confirm('Eliminar este dossier e todas as notas? Esta operação não pode ser desfeita.'))void mutate({action:'delete',dossierId:selected},'');}}>Eliminar dossier</button>
 <p>As versões são registos separados, ordenados pela data. Não substituem o original; pode eliminá-las. Não é um arquivo de auditoria imutável. Apenas a sua conta tem acesso a este dossier; não existe partilha de equipa nesta área.</p><h3>{kind==='clause'?'Guardar nova versão':'Guardar nota ou relatório'}</h3><form onSubmit={e=>{e.preventDefault();void mutate({action:'save',id:crypto.randomUUID(),dossierId:selected,title:noteTitle,body:kind==='clause'?JSON.stringify({type:'lic-clause-v1',text:body,usage,approved}):body,sources});}}><label>Título<input required maxLength={160} value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/></label><label>Texto<textarea required rows={8} maxLength={kind==='clause'?10000:80000} value={body} onChange={e=>setBody(e.target.value)}/></label>{kind==='clause'&&<><label>Contexto e limites de utilização<textarea maxLength={2000} value={usage} onChange={e=>setUsage(e.target.value)}/></label><label className="analysis-consent"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Revi e aprovo esta versão para o contexto indicado (declaração pessoal).</label></>}<SourceEvidence sources={sources} onChange={setSources} disabled={busy}/><button className="btn btn-primary" disabled={busy}>Guardar</button></form>
 {diff&&<details><summary>Comparar os dois últimos registos</summary><p>Diferenças textuais; não comprovam alterações na lei.</p><h4>Acrescentado</h4><pre style={{whiteSpace:'pre-wrap'}}>{diff.added.join('\n')||'Sem diferenças'}</pre><h4>Retirado</h4><pre style={{whiteSpace:'pre-wrap'}}>{diff.removed.join('\n')||'Sem diferenças'}</pre></details>}
 {entries.map(entry=><article className="assistant-turn" key={entry.id}><h3>{entry.title}</h3><p>{new Date(entry.created_at).toLocaleString('pt-PT')}</p><ClauseBody kind={kind} body={entry.body}/><button className="btn btn-secondary" disabled={busy} onClick={()=>{if((body||sources.length)&&!confirm('Substituir o rascunho não guardado?'))return;const v=readClause(entry.body);setBody(kind==='clause'?v.text:entry.body);setUsage(v.usage);setApproved(false);setSources(entry.sources.map(s=>({...s,reviewed:false})));setNoteTitle(('Revisão de '+entry.title).slice(0,160));}}>Preparar nova versão sem alterar o original</button>{entry.sources.filter(s=>safeSourceUrl(s.url)).map((s,i)=><p key={i}><a href={safeSourceUrl(s.url)!} target="_blank" rel="noopener noreferrer">{s.title}</a><span style={{display:'block',whiteSpace:'pre-wrap'}}>{sourceEvidence(s).split('\n').slice(1).join('\n')}</span></p>)}<button disabled={busy} onClick={()=>{if(confirm('Eliminar esta nota definitivamente?'))void mutate({action:'delete-entry',dossierId:selected,id:entry.id});}}>Eliminar nota</button></article>)}</section>}
 </AppShell>;
}

function ClauseBody({kind,body}:{kind:string;body:string}){const c=readClause(body);return kind==='clause'?<><p>{c.approved?'Aprovada pelo utilizador':'Rascunho — não aprovada'}</p><p style={{whiteSpace:'pre-wrap'}}>Contexto: {c.usage||'Não indicado'}</p><div style={{whiteSpace:'pre-wrap'}}>{c.text}</div></>:<div style={{whiteSpace:'pre-wrap'}}>{body}</div>;}
