"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { AppShell } from './app-shell';
import { createClient } from '@/lib/supabase/client';
import { compareReports, exportDossier, type Dossier, type LibraryEntry } from '@/lib/library';
import { safeSourceUrl } from '@/lib/legal-research';
import { downloadReport } from './assistant-panel';
export function ResearchLibrary({kind}:{kind:'dossier'|'watch'}) {
 const [dossiers,setDossiers]=useState<Dossier[]>([]),[entries,setEntries]=useState<LibraryEntry[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[noteTitle,setNoteTitle]=useState(''),[body,setBody]=useState(''),[url,setUrl]=useState('');
 const epoch=useRef(0),lock=useRef(false);
 async function load(id='') { const version=++epoch.current; setBusy(true); try { const r=await fetch('/api/library'+(id?'?id='+encodeURIComponent(id):'')); const d=await r.json(); if(version!==epoch.current)return; if(!r.ok)throw Error(d.error);setDossiers(d.dossiers);setEntries(d.entries??[]);setSelected(id);setError(''); }catch(e){if(version===epoch.current)setError(e instanceof Error?e.message:'Não foi possível carregar.');}finally{if(version===epoch.current)setBusy(false);} }
 useEffect(()=>{ void load(); const client=createClient(); const subscription=client?.auth.onAuthStateChange(()=>{epoch.current++;setEntries([]);setDossiers([]);setSelected('');setBody('');setTitle('');setDescription('');setNoteTitle('');setUrl('');void load();});return()=>{epoch.current++;subscription?.data.subscription.unsubscribe();};},[]);
 async function mutate(payload:object,next=selected) { if(lock.current)return;lock.current=true;setBusy(true);setError('');const version=epoch.current;try{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(version!==epoch.current)return;if(!r.ok)throw Error(d.error);setBody('');setNoteTitle('');setUrl('');await load(next);}catch(e){if(version===epoch.current)setError(e instanceof Error?e.message:'Falha ao guardar.');}finally{lock.current=false;setBusy(false);} }
 const current=dossiers.find(d=>d.id===selected); const diff=kind==='watch'&&entries.length>=2?compareReports(entries[1].body,entries[0].body):null;
 return <AppShell><h1>{kind==='watch'?'Alertas legislativos — consulta manual':'Dossiers de pesquisa'}</h1><p>Área pessoal. Guarde apenas conteúdo que tem autorização para conservar. Não existe envio automático para a IA.</p>{kind==='watch'&&<p>Sem monitorização contínua ou e-mails. <Link href="/services/watch">Consultar alterações com IA</Link>: indique o tema e o período, reveja as fontes e guarde o relatório abaixo. A IA paga permanece bloqueada nesta fase.</p>}
 {error&&<p role="alert">{error} <Link href="/login">Entrar</Link> · <Link href="/setup/services">Configurar armazenamento</Link></p>}
 <section className="card team-panel"><h2>{kind==='watch'?'Novo tema':'Novo dossier'}</h2><form onSubmit={e=>{e.preventDefault();const id=crypto.randomUUID();void mutate({action:'create',id,kind,title,description},id);}}><label>Título<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Descrição / período de interesse<textarea maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>Criar</button></form></section>
 <label>Escolher<select disabled={busy} value={selected} onChange={e=>void load(e.target.value)}><option value="">Seleccione</option>{dossiers.filter(d=>d.kind===kind).map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
 {current&&<section className="card team-panel"><h2>{current.title}</h2><p>{current.description}</p><button className="btn btn-secondary" onClick={()=>downloadReport(exportDossier(current,entries),'dossier-lic.txt')}>Exportar dossier</button><button className="btn btn-secondary" disabled={busy} onClick={()=>{if(confirm('Eliminar este dossier e todas as notas? Esta operação não pode ser desfeita.'))void mutate({action:'delete',dossierId:selected},'');}}>Eliminar dossier</button>
 <h3>Guardar nota ou relatório</h3><form onSubmit={e=>{e.preventDefault();void mutate({action:'save',id:crypto.randomUUID(),dossierId:selected,title:noteTitle,body,sources:url?[{title:'Fonte indicada pelo utilizador',url}]:[]});}}><label>Título<input required maxLength={160} value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/></label><label>Texto<textarea required rows={8} maxLength={80000} value={body} onChange={e=>setBody(e.target.value)}/></label><label>Fonte (URL opcional)<input type="url" maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>Guardar</button></form>
 {diff&&<details><summary>Comparar os dois últimos registos</summary><p>Diferenças textuais; não comprovam alterações na lei.</p><h4>Acrescentado</h4><pre style={{whiteSpace:'pre-wrap'}}>{diff.added.join('\n')||'Sem diferenças'}</pre><h4>Retirado</h4><pre style={{whiteSpace:'pre-wrap'}}>{diff.removed.join('\n')||'Sem diferenças'}</pre></details>}
 {entries.map(entry=><article className="assistant-turn" key={entry.id}><h3>{entry.title}</h3><p>{new Date(entry.created_at).toLocaleString('pt-PT')}</p><div style={{whiteSpace:'pre-wrap'}}>{entry.body}</div>{entry.sources.filter(s=>safeSourceUrl(s.url)).map((s,i)=><p key={i}><a href={safeSourceUrl(s.url)!} target="_blank" rel="noopener noreferrer">{s.title}</a></p>)}<button disabled={busy} onClick={()=>{if(confirm('Eliminar esta nota definitivamente?'))void mutate({action:'delete-entry',dossierId:selected,id:entry.id});}}>Eliminar nota</button></article>)}</section>}
 </AppShell>;
}
