"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { AppShell } from './app-shell';
import { createClient } from '@/lib/supabase/client';
import { compareReports, exportDossier, type Dossier, type LibraryEntry, type LibrarySource, sourceEvidence,filterEntries,linkedDocument } from '@/lib/library';
import { readClause } from '@/lib/clauses';
import { safeSourceUrl } from '@/lib/legal-research';
import { downloadReport } from './assistant-panel';
import { DossierSharing } from './dossier-sharing';
import { SourceEvidence } from './source-evidence';
import { useUnsavedWork } from './use-unsaved-work';
import {ReportActions} from './report-actions';
import {DossierDocuments} from './dossier-documents';
import {CaseWorkspace} from './case-workspace';
import {LibrarySearch} from './library-search';
import {readCaseRecord,recordKinds} from '@/lib/case-workspace';
export function ResearchLibrary({kind}:{kind:'dossier'|'watch'|'clause'}) {
 const [dossiers,setDossiers]=useState<Dossier[]>([]),[entries,setEntries]=useState<LibraryEntry[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[noteTitle,setNoteTitle]=useState(''),[body,setBody]=useState(''),[sources,setSources]=useState<LibrarySource[]>([]);
 const [caseDirty,setCaseDirty]=useState(false);
 const [approved,setApproved]=useState(false),[usage,setUsage]=useState('');
 const [filter,setFilter]=useState(''),[revisionOf,setRevisionOf]=useState<string|null>(null);
 useUnsavedWork(Boolean(body||noteTitle||sources.length));
 const [entryQuery,setEntryQuery]=useState(''),[entryScope,setEntryScope]=useState<'all'|'sources'|'documents'|'revisions'>('all');
 const epoch=useRef(0),lock=useRef(false);
 async function load(id='') { const version=++epoch.current; setBusy(true); try { const r=await fetch('/api/library'+(id?'?id='+encodeURIComponent(id):'')); const d=await r.json(); if(version!==epoch.current)return; if(!r.ok)throw Error(d.error);setDossiers(d.dossiers);setEntries(d.entries??[]);setSelected(id);setError(''); }catch(e){if(version===epoch.current)setError(e instanceof Error?e.message:'Não foi possível carregar.');}finally{if(version===epoch.current)setBusy(false);} }
 useEffect(()=>{ void load(); const client=createClient(); const subscription=client?.auth.onAuthStateChange((event)=>{if(event!=='SIGNED_OUT'&&event!=='SIGNED_IN')return;epoch.current++;setFilter('');setApproved(false);setUsage('');setEntries([]);setDossiers([]);setSelected('');setBody('');setTitle('');setDescription('');setNoteTitle('');setSources([]);setRevisionOf(null);void load();});return()=>{epoch.current++;subscription?.data.subscription.unsubscribe();};},[]);
async function mutate(payload:{action:string;[key:string]:unknown},next=selected) { if(lock.current)return;lock.current=true;setBusy(true);setError('');const version=epoch.current;try{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(version!==epoch.current)return;if(!r.ok)throw Error(d.error);if(['save','create','delete'].includes(payload.action)){setBody('');setApproved(false);setUsage('');setNoteTitle('');setSources([]);setRevisionOf(null);}await load(next);}catch(e){if(version===epoch.current)setError(e instanceof Error?e.message:'Falha ao guardar.');}finally{lock.current=false;setBusy(false);} }
 const current=dossiers.find(d=>d.id===selected); const diff=kind==='watch'&&entries.length>=2?compareReports(entries[1].body,entries[0].body):null;
 return <AppShell><h1>{kind==='watch'?'Alertas legislativos — consulta manual' :kind==='clause'?'Biblioteca pessoal de cláusulas':'Dossiers de pesquisa'}</h1><p>Dossiers pessoais e partilhados consigo. Guarde apenas conteúdo que tem autorização para conservar. Não existe envio automático para a IA.</p>{kind==='watch'&&<p>Sem monitorização contínua ou e-mails. <Link href="/services/watch">Consultar alterações com IA</Link>: indique o tema e o período, reveja as fontes e guarde o relatório abaixo. A IA paga permanece bloqueada nesta fase.</p>}
 {error&&<p role="alert">{error} <Link href="/login">Entrar</Link> · <Link href="/setup/services">Configurar armazenamento</Link></p>}
 {kind==='clause'&&<p>Cada cláusula reúne versões guardadas separadamente. A aprovação é uma declaração sua, não uma validação jurídica automática. As versões podem ser eliminadas; isto não é um arquivo de auditoria imutável.</p>}
 <section className="card team-panel"><h2>{kind==='watch'?'Novo tema':kind==='clause'?'Nova cláusula':'Novo dossier'}</h2><form onSubmit={e=>{e.preventDefault();const id=crypto.randomUUID();void mutate({action:'create',id,kind,title,description},id);}}><label>Título<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Descrição / período de interesse<textarea maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>Criar</button></form></section>
 <LibrarySearch onOpen={id=>{if((caseDirty||body||noteTitle)&&!confirm('Descartar o rascunho?'))return;setBody('');setNoteTitle('');void load(id);}}/>
 <label>Pesquisar título ou contexto<input type="search" maxLength={160} value={filter} onChange={e=>setFilter(e.target.value)}/></label>
 <label>Escolher<select disabled={busy} value={selected} onChange={e=>{if((caseDirty||body||sources.length||noteTitle)&&!confirm('Descartar o rascunho não guardado?'))return;setBody('');setUsage('');setApproved(false);setNoteTitle('');setSources([]);setRevisionOf(null);void load(e.target.value);}}><option value="">Seleccione</option>{dossiers.filter(d=>d.kind===kind&&(!filter||`${d.title} ${d.description}`.toLocaleLowerCase('pt-PT').includes(filter.toLocaleLowerCase('pt-PT')))).map(d=><option key={d.id} value={d.id}>{d.title}{d.canManage===false?(d.canEdit?' — equipa (edição)':' — equipa (leitura)'):''}</option>)}</select></label>
 {current&&<section className="card team-panel"><h2>{current.title}</h2><p>{current.description}</p><button className="btn btn-secondary" onClick={()=>downloadReport(exportDossier(current,entries),'dossier-lic.txt')}>{kind==='clause'?'Exportar todas as versões':'Exportar dossier'}</button><button className="btn btn-secondary" disabled={busy||current.canManage===false} onClick={()=>{if(confirm('Eliminar este dossier e todas as notas? Esta operação não pode ser desfeita.'))void mutate({action:'delete',dossierId:selected},'');}}>Eliminar dossier</button>
 <ReportActions title={current.title} text={exportDossier(current,entries)}/>
 {kind==='dossier'&&<CaseWorkspace onDirty={setCaseDirty} key={selected} entries={entries} disabled={busy||current.canEdit===false} onSave={async(title,record,revision,id)=>{if(lock.current)throw Error('BUSY');lock.current=true;setBusy(true);const version=epoch.current;try{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',id,dossierId:selected,title,body:JSON.stringify(record),sources:[],revisionOf:revision})});if(version!==epoch.current)throw Error('SESSION_CHANGED');if(!r.ok)throw Error('SAVE');await load(selected);}finally{lock.current=false;if(version===epoch.current)setBusy(false);}}}/>}
 {current.canManage!==false&&<details><summary>Editar título e descrição</summary><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void mutate({action:'rename',dossierId:selected,title:data.get('title'),description:data.get('description')});}} key={current.id+current.title+current.description}><label>Título do dossier<input name="title" required maxLength={160} defaultValue={current.title}/></label><label>Descrição do dossier<textarea name="description" maxLength={4000} defaultValue={current.description}/></label><button className="btn btn-secondary" disabled={busy}>Guardar título e descrição</button></form></details>}
 {kind==='dossier'&&current.canEdit!==false&&<DossierDocuments key={selected} disabled={busy||!!body||!!noteTitle||sources.length>0} onAttach={item=>void mutate({action:'save',id:crypto.randomUUID(),dossierId:selected,title:('Documento — '+item.filename).slice(0,160),body:JSON.stringify({type:'lic-document-link-v1',contractId:item.id,filename:item.filename}),sources:[]})}/>}
 <p>As versões são registos separados, ordenados pela data. Não substituem o original; pode eliminá-las. Não é um arquivo de auditoria imutável. O titular gere permissões de leitura ou edição. As revisões indicam a versão anterior e a conta autora; só o titular pode eliminar registos.</p>{current.canManage!==false?<DossierSharing key={selected} id={selected}/>:<p>{current.canEdit?'Partilhado consigo — pode acrescentar notas e novas versões.':'Partilhado consigo — apenas leitura e exportação.'}</p>}<fieldset disabled={busy||current.canEdit===false}><legend>Notas e versões</legend>{revisionOf&&<p>A rever o registo {revisionOf}. O original será conservado. <button type="button" onClick={()=>setRevisionOf(null)}>Guardar como nota independente</button></p>}<h3>{kind==='clause'?'Guardar nova versão':'Guardar nota ou relatório'}</h3><form onSubmit={e=>{e.preventDefault();void mutate({action:'save',id:crypto.randomUUID(),dossierId:selected,title:noteTitle,body:kind==='clause'?JSON.stringify({type:'lic-clause-v1',text:body,usage,approved}):body,sources,revisionOf});}}><label>Título<input required maxLength={160} value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/></label><label>Texto<textarea required rows={8} maxLength={kind==='clause'?10000:80000} value={body} onChange={e=>setBody(e.target.value)}/></label>{kind==='clause'&&<><label>Contexto e limites de utilização<textarea maxLength={2000} value={usage} onChange={e=>setUsage(e.target.value)}/></label><label className="analysis-consent"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Revi e aprovo esta versão para o contexto indicado (declaração pessoal).</label></>}<SourceEvidence sources={sources} onChange={setSources} disabled={busy}/><button className="btn btn-primary" disabled={busy}>Guardar</button></form></fieldset>
 {diff&&<details><summary>Comparar os dois últimos registos</summary><p>Diferenças textuais; não comprovam alterações na lei.</p><h4>Acrescentado</h4><pre style={{whiteSpace:'pre-wrap'}}>{diff.added.join('\n')||'Sem diferenças'}</pre><h4>Retirado</h4><pre style={{whiteSpace:'pre-wrap'}}>{diff.removed.join('\n')||'Sem diferenças'}</pre></details>}
 <section className="dossier-search"><h3>Pesquisar neste dossier</h3><label>Texto, título ou fonte<input type="search" maxLength={200} value={entryQuery} onChange={e=>setEntryQuery(e.target.value)}/></label><label>Tipo de registo<select value={entryScope} onChange={e=>setEntryScope(e.target.value as typeof entryScope)}><option value="all">Todos</option><option value="sources">Com fontes</option><option value="documents">Documentos ligados</option><option value="revisions">Revisões</option></select></label><p role="status">{filterEntries(entries,entryQuery,entryScope).length} de {entries.length} registos. Pesquisa local, sem chamadas à IA.</p></section>
 {filterEntries(entries,entryQuery,entryScope).map(entry=><article className="assistant-turn" id={entry.id} key={entry.id}><h3>{entry.title}</h3><p>{new Date(entry.created_at).toLocaleString('pt-PT')}</p><p>Autor (ID da conta): {entry.created_by||'não registado nesta versão antiga'}{entry.revision_of&&<> · Revisão de <a href={'#'+entry.revision_of}>{entry.revision_of}</a></>}</p><ClauseBody kind={kind} body={entry.body}/>{!readCaseRecord(entry.body)&&<button className="btn btn-secondary" disabled={busy||current.canEdit===false} onClick={()=>{if((body||sources.length)&&!confirm('Substituir o rascunho não guardado?'))return;const v=readClause(entry.body);setBody(kind==='clause'?v.text:entry.body);setUsage(v.usage);setApproved(false);setSources(entry.sources.map(s=>({...s,reviewed:false})));setRevisionOf(entry.id);setNoteTitle(('Revisão de '+entry.title).slice(0,160));}}>Preparar nova versão sem alterar o original</button>}{entry.sources.filter(s=>safeSourceUrl(s.url)).map((s,i)=><p key={i}><a href={safeSourceUrl(s.url)!} target="_blank" rel="noopener noreferrer">{s.title}</a><span style={{display:'block',whiteSpace:'pre-wrap'}}>{sourceEvidence(s).split('\n').slice(1).join('\n')}</span></p>)}<button disabled={busy||current.canManage===false} onClick={()=>{if(confirm('Eliminar esta nota definitivamente?'))void mutate({action:'delete-entry',dossierId:selected,id:entry.id});}}>Eliminar nota</button></article>)}</section>}
 </AppShell>;
}

function ClauseBody({kind,body}:{kind:string;body:string}){const record=readCaseRecord(body);if(record)return <details><summary>{recordKinds[record.kind]} — versão guardada</summary><p>{record.reference} · {record.date||'Data por indicar'}</p><pre className="readable-pre">{record.text}</pre></details>;const doc=linkedDocument(body);if(doc)return <p><Link className="source-link" href={'/contracts/'+doc.contractId}>Abrir documento — {doc.filename}</Link><br/>Acesso sujeito às permissões da empresa do documento. Se necessário, seleccione a empresa correcta em Contratos.</p>;const c=readClause(body);return kind==='clause'?<><p>{c.approved?'Aprovada pelo utilizador':'Rascunho — não aprovada'}</p><p style={{whiteSpace:'pre-wrap'}}>Contexto: {c.usage||'Não indicado'}</p><div style={{whiteSpace:'pre-wrap'}}>{c.text}</div></>:<div style={{whiteSpace:'pre-wrap'}}>{body}</div>;}
