"use client";
import Link from "next/link";
import { useState } from "react";
import { AppShell } from "./app-shell";

export function SqlSetup({ sql, analysis = false }: { sql: string; analysis?: boolean }) {
  const [message, setMessage] = useState("");
  async function copy() {
    try { await navigator.clipboard.writeText(sql); setMessage("Código copiado. Agora cole-o numa nova consulta no SQL Editor do Supabase e clique em Run."); }
    catch { setMessage("Clique no texto abaixo, prima ⌘ + A e depois ⌘ + C para o copiar."); }
  }
  return <AppShell><div className="eyebrow">Preparação</div><h1 className="workspace-title">{analysis ? "Activar análise com IA" : "Activar contratos e políticas"}</h1><section className="card team-panel"><p>{analysis ? "Esta actualização cria o registo privado de análises e os limites de utilização. Execute-a depois das actualizações 001, 002 e 003. Não apaga os seus documentos." : "Esta actualização prepara os ficheiros privados e as políticas da sua empresa. As actualizações anteriores de empresa e equipa devem estar instaladas."}</p><ol><li>Clique em <strong>Copiar código SQL</strong>.</li><li>No seu projecto Supabase, abra <strong>SQL Editor</strong> e clique no <strong>+</strong> ao lado da consulta actual.</li><li>Cole o código nessa consulta nova e clique em <strong>Run</strong>.</li><li>Quando aparecer <strong>Success</strong>, {analysis ? "configure as duas chaves privadas indicadas abaixo." : "volte ao site para criar uma política ou carregar um contrato."}</li></ol><button onClick={copy} className="btn btn-primary">Copiar código SQL</button>{message && <p role="status" className="team-notice">{message}</p>}<details style={{ marginTop: 20 }}><summary>Ver código completo</summary><label htmlFor="setup-sql">Código da actualização {analysis ? "004" : "003"}</label><textarea id="setup-sql" readOnly rows={18} value={sql} onFocus={event => event.target.select()} spellCheck={false}/></details>
    {analysis && <div className="workspace-row"><h2>Chaves apenas no servidor</h2><p>No ficheiro <code>.env.local</code>, guarde <code>OPENAI_API_KEY</code> e <code>SUPABASE_SERVICE_ROLE_KEY</code>. A primeira permite analisar; a segunda permite ao servidor guardar resultados sem permitir que o navegador os falsifique.</p><p>No Supabase, abra as definições do projecto e a área <strong>API Keys</strong>. Use uma chave secreta de servidor (secret ou service_role), nunca a publishable neste campo. Não partilhe esta chave por mensagem ou comentário.</p><p>O nome da variável deve ser exactamente <code>SUPABASE_SERVICE_ROLE_KEY</code>, sem <code>NEXT_PUBLIC_</code>. Mantenha as outras variáveis. Reinicie o servidor depois de guardar.</p><p>Por fim, abra <strong>Contratos</strong>, escolha um PDF até 10 MB, leia a autorização e clique em <strong>Analisar contrato</strong>. Comece com um contrato fictício, sem dados pessoais. A conta API precisa de saldo.</p></div>}
    <div className="workspace-toolbar" style={{ marginTop: 20 }}><Link href="/policies" className="btn btn-secondary">Abrir políticas</Link><Link href={analysis ? "/contracts" : "/contracts/new"} className="btn btn-secondary">{analysis ? "Abrir contratos" : "Carregar contrato"}</Link></div></section></AppShell>;
}
