export const reviewCriteria=['Fontes existem e sustentam as afirmações','Versão e vigência confirmadas','Jurisdição e aplicabilidade correctas','Sem afirmações ou citações inventadas','Limitações e incertezas explícitas','Resposta útil e completa para o caso'] as const;
export type ReviewScore='pending'|'pass'|'fail'|'na';
export function qualityReport(input:{caseName:string;reviewer:string;model:string;answer:string;notes:string;scores:ReviewScore[];seconds:string;cost:string}){
 if(!input.caseName.trim()||!input.reviewer.trim()||!input.answer.trim()||input.caseName.length>200||input.reviewer.length>120||input.model.length>200||input.answer.length>60000||input.notes.length>12000||input.scores.length!==reviewCriteria.length||input.scores.some(s=>!['pending','pass','fail','na'].includes(s)))throw Error('Preencha o caso, o revisor e a resposta, respeitando os limites.');
 for(const v of [input.seconds,input.cost])if(v!==''&&(!/^\d{1,8}(?:[.,]\d{1,6})?$/.test(v)||!Number.isFinite(Number(v.replace(',','.')))))throw Error('Indique tempo e custo não negativos, ou deixe em branco.');
 const labels={pending:'Por avaliar',pass:'Conforme — declaração do revisor',fail:'Não conforme',na:'Não aplicável — justificar nas notas'};
 if(input.scores.some(s=>s!=='pending')&&!input.notes.trim())throw Error('Registe a evidência e a justificação da avaliação nas notas.');
 const status=input.scores.includes('fail')?'REPROVADA':input.scores.includes('pending')?'INCOMPLETA':input.scores.every(s=>s==='na')?'SEM CRITÉRIOS APLICÁVEIS — não avaliada':'AVALIADA MANUALMENTE — não constitui certificação';
 return `LIC — Ficha de avaliação humana\nCaso: ${input.caseName}\nRevisor (identidade não verificada): ${input.reviewer}\nModelo / versão declarados: ${input.model||'Não indicado'}\nData: ${new Date().toISOString()}\nEstado: ${status}\nTempo declarado: ${input.seconds||'Não medido'} segundos\nCusto declarado: ${input.cost||'Não medido'} EUR\n\n${reviewCriteria.map((c,i)=>`${c}: ${labels[input.scores[i]]}`).join('\n')}\n\nResposta avaliada:\n${input.answer}\n\nEvidência, erros, referências e justificação dos itens não aplicáveis:\n${input.notes||'Não indicada'}\n\nUma avaliação isolada não demonstra superioridade ou segurança jurídica. Os valores não são medições automáticas nem consumo facturado pela plataforma.`;
}
