import Link from 'next/link';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {AppShell} from '@/components/app-shell';
import {ServicesSetup} from '@/components/services-setup';
import {createClient} from '@/lib/supabase/server';
import {createAdminClient} from '@/lib/supabase/admin';
import {isBillingTester} from '@/lib/billing';
import {measuredResearchModel} from '@/lib/model-routing';
export const dynamic='force-dynamic';
export const metadata={title:'Operação técnica | LIC',robots:{index:false,follow:false}};
export default async function Page(){
 const client=await createClient();const user=(await client?.auth.getUser())?.data.user;
 if(!user?.email_confirmed_at||!isBillingTester(user.email,(process.env.BILLING_TEST_EMAIL||'').trim().toLowerCase()))return <AppShell><h1>Configuração reservada</h1><Link href="/login?next=/setup/workspace">Entrar</Link></AppShell>;
 const db=createAdminClient();const receipts=db?await db.from('research_delivery_receipts').select('received_at,completed_at').order('received_at',{ascending:false}).limit(20):null;
 const audit=await client!.from('research_audit').select('operation,dossier_id,entry_id,actor_id,occurred_at').order('occurred_at',{ascending:false}).limit(50);
 const installed=!!receipts&&!receipts.error&&!audit.error;
 const pending=db?await db.from('research_jobs').select('id,state,updated_at').in('state',['starting','draft','review_starting','review']).lt('updated_at',new Date(Date.now()-5*60000).toISOString()).limit(30):null;
 return <AppShell><div className="eyebrow">Reservado ao titular · sem geração</div><h1>Operação técnica</h1><section className="card team-panel"><h2>Instalação única</h2><p>{installed?'Estrutura 020 detectada. Não precisa de repetir o SQL.':'Execute a actualização 020 após as anteriores (incluindo 019). Não altera saldos, tarifas ou activação comercial.'}</p>{!installed&&<ServicesSetup sql={readFileSync(join(process.cwd(),'supabase/migrations/020_workspace.sql'),'utf8')}/>}<p>Notificações OpenAI: {process.env.OPENAI_WEBHOOK_SECRET?'segredo configurado; confirme entregas abaixo':'segredo ainda não configurado'}.</p><p>Encaminhamento por avaliação: {measuredResearchModel(process.env.AI_MODEL_EVALUATIONS_JSON)||'sem conjunto aprovado e actual; escolha manual mantida'}.</p></section>
 <section className="card team-panel"><h2>Processamento sem o navegador</h2><ol><li>No projecto da API OpenAI que fornece a chave usada pela LIC, crie um webhook para <code>https://legal-intelligence-company.vercel.app/api/research/webhook</code>.</li><li>Subscreva <code>response.completed</code>, <code>response.failed</code>, <code>response.incomplete</code> e <code>response.cancelled</code>.</li><li>Guarde o segredo de assinatura em <code>OPENAI_WEBHOOK_SECRET</code> no servidor Vercel e publique. Não o partilhe em mensagens.</li><li>Confirme uma entrega real assinada. Um teste com ID fictício não corresponde a um pedido LIC e será recusado para repetição. A pesquisa só está confirmada como independente do navegador depois de um ensaio ponta a ponta.</li></ol><p>A assinatura, a conta guardada, os interruptores de execução e as reservas continuam a ser verificados. Uma tentativa de geração incerta não é repetida. A OpenAI pode repetir notificações, mas a transição guardada impede gerar uma segunda revisão.</p><p>Recuperação operacional adicional: um agendador pode chamar <code>/api/maintenance/research</code> a cada minuto, com <code>Authorization: Bearer CRON_SECRET</code>. Requer alojamento que suporte essa frequência. Não foi contratado um serviço nem alterado o plano de alojamento. Processa no máximo dois pedidos já autorizados por execução.</p><p><a href="https://developers.openai.com/api/docs/guides/webhooks">Documentação oficial das notificações</a></p></section>
 <section className="card team-panel"><h2>Entregas recentes</h2>{receipts?.data?.length?<ul>{receipts.data.map((r,i)=><li key={i}>{r.received_at} — {r.completed_at?'tratada':'pendente / requer repetição'}</li>)}</ul>:<p>Ainda não há entregas registadas. Ter o segredo configurado não comprova funcionamento.</p>}<h3>Pedidos há mais de cinco minutos sem avanço</h3>{pending?.data?.length?<ul>{pending.data.map(r=><li key={r.id}>{r.id} — {r.state}</li>)}</ul>:<p>{pending?.error?'Estado indisponível.':'Nenhum encontrado.'}</p>}</section>
 <section className="card team-panel"><h2>Auditoria dos seus dossiers</h2><p>Últimos 50 eventos. Guarda IDs, operação e data, não o texto dos documentos. Apenas o titular lê este registo; membros não o podem alterar. Retenção prevista: 90 dias, pela limpeza programada. Administradores da base de dados continuam a poder alterar dados; não é um arquivo inviolável.</p>{audit.data?.map((r,i)=><p key={i}>{r.occurred_at} · {r.operation} · dossier {r.dossier_id} · autor {r.actor_id||'conta eliminada'}</p>)}</section>
 <section className="card team-panel"><h2>Ferramentas de trabalho</h2><div className="workspace-toolbar"><Link className="btn btn-primary" href="/library">Dossiers e fontes por data</Link><Link className="btn btn-secondary" href="/document-workbench">PDF e OCR</Link><Link className="btn btn-secondary" href="/word-review">Word e regras de revisão</Link><Link className="btn btn-secondary" href="/benchmarks">Laboratório comparativo</Link></div></section></AppShell>;
}
